// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdminRole generated by hbm2java
 */
public class AdminRole implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer updater;
	private Date updateTime;
	private String remark;
	private Set<Admin> admins = new HashSet<Admin>(0);
	private Set<AdminRoleModule> adminRoleModules = new HashSet<AdminRoleModule>(
			0);

	public AdminRole() {
	}

	public AdminRole(String name, Date updateTime) {
		this.name = name;
		this.updateTime = updateTime;
	}

	public AdminRole(String name, Integer updater, Date updateTime,
			String remark, Set<Admin> admins,
			Set<AdminRoleModule> adminRoleModules) {
		this.name = name;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.admins = admins;
		this.adminRoleModules = adminRoleModules;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Admin> getAdmins() {
		return this.admins;
	}

	public void setAdmins(Set<Admin> admins) {
		this.admins = admins;
	}

	public Set<AdminRoleModule> getAdminRoleModules() {
		return this.adminRoleModules;
	}

	public void setAdminRoleModules(Set<AdminRoleModule> adminRoleModules) {
		this.adminRoleModules = adminRoleModules;
	}

}
