// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CommodityProvider generated by hbm2java
 */
public class CommodityProvider implements java.io.Serializable {

	private Integer id;
	private String name;
	private String phone;
	private String linkman;
	private String linkmanPhone;
	private String linkmanMobile;
	private String address;
	private Integer updater;
	private Date updateTime;
	private String remark;
	private Set<Commodity> commodities = new HashSet<Commodity>(0);

	public CommodityProvider() {
	}

	public CommodityProvider(String name, Date updateTime) {
		this.name = name;
		this.updateTime = updateTime;
	}

	public CommodityProvider(String name, String phone, String linkman,
			String linkmanPhone, String linkmanMobile, String address,
			Integer updater, Date updateTime, String remark,
			Set<Commodity> commodities) {
		this.name = name;
		this.phone = phone;
		this.linkman = linkman;
		this.linkmanPhone = linkmanPhone;
		this.linkmanMobile = linkmanMobile;
		this.address = address;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.commodities = commodities;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinkmanPhone() {
		return this.linkmanPhone;
	}

	public void setLinkmanPhone(String linkmanPhone) {
		this.linkmanPhone = linkmanPhone;
	}

	public String getLinkmanMobile() {
		return this.linkmanMobile;
	}

	public void setLinkmanMobile(String linkmanMobile) {
		this.linkmanMobile = linkmanMobile;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Commodity> getCommodities() {
		return this.commodities;
	}

	public void setCommodities(Set<Commodity> commodities) {
		this.commodities = commodities;
	}

}
