// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commodity generated by hbm2java
 */
public class Commodity implements java.io.Serializable {

	private Integer id;
	private Area area;
	private Commodity commodity;
	private CommodityProvider commodityProvider;
	private CommodityCategory commodityCategory;
	private String name;
	private String shortName;
	private String summary;
	private String standard;
	private String priceUnit;
	private BigDecimal priceQuantity;
	private String picturePath;
	private Integer priority;
	private String commendCode;
	private String status;
	private BigDecimal originalPrice;
	private BigDecimal price;
	private BigDecimal price1;
	private BigDecimal price2;
	private BigDecimal price3;
	private BigDecimal price4;
	private BigDecimal price5;
	private Integer point;
	private Integer updater;
	private Date updateTime;
	private String remark;
	private String unit;
	private BigDecimal quantity;
	private Integer minimumBuy;
	private Set<CommodityOrderItem> commodityOrderItems = new HashSet<CommodityOrderItem>(
			0);
	private Set<LabelCommodity> labelCommodities = new HashSet<LabelCommodity>(
			0);
	private Set<Commodity> commodities = new HashSet<Commodity>(0);
	private Set<CommodityPromotion> commodityPromotions = new HashSet<CommodityPromotion>(
			0);
	private Set<CommodityPicture> commodityPictures = new HashSet<CommodityPicture>(
			0);
	private Set<FavoriteCommodity> favoriteCommodities = new HashSet<FavoriteCommodity>(
			0);
	private Set<CommodityDetail> commodityDetails = new HashSet<CommodityDetail>(
			0);
	private Set<CommodityComment> commodityComments = new HashSet<CommodityComment>(
			0);

	public Commodity() {
	}

	public Commodity(Area area, CommodityCategory commodityCategory,
			String name, String shortName, String picturePath,
			String commendCode, String status, BigDecimal price, Integer point,
			Date updateTime, String unit, BigDecimal quantity,
			Integer minimumBuy) {
		this.area = area;
		this.commodityCategory = commodityCategory;
		this.name = name;
		this.shortName = shortName;
		this.picturePath = picturePath;
		this.commendCode = commendCode;
		this.status = status;
		this.price = price;
		this.point = point;
		this.updateTime = updateTime;
		this.unit = unit;
		this.quantity = quantity;
		this.minimumBuy = minimumBuy;
	}

	public Commodity(Area area, Commodity commodity,
			CommodityProvider commodityProvider,
			CommodityCategory commodityCategory, String name, String shortName,
			String summary, String standard, String priceUnit,
			BigDecimal priceQuantity, String picturePath, Integer priority,
			String commendCode, String status, BigDecimal originalPrice,
			BigDecimal price, BigDecimal price1, BigDecimal price2,
			BigDecimal price3, BigDecimal price4, BigDecimal price5,
			Integer point, Integer updater, Date updateTime, String remark,
			String unit, BigDecimal quantity, Integer minimumBuy,
			Set<CommodityOrderItem> commodityOrderItems,
			Set<LabelCommodity> labelCommodities, Set<Commodity> commodities,
			Set<CommodityPromotion> commodityPromotions,
			Set<CommodityPicture> commodityPictures,
			Set<FavoriteCommodity> favoriteCommodities,
			Set<CommodityDetail> commodityDetails,
			Set<CommodityComment> commodityComments) {
		this.area = area;
		this.commodity = commodity;
		this.commodityProvider = commodityProvider;
		this.commodityCategory = commodityCategory;
		this.name = name;
		this.shortName = shortName;
		this.summary = summary;
		this.standard = standard;
		this.priceUnit = priceUnit;
		this.priceQuantity = priceQuantity;
		this.picturePath = picturePath;
		this.priority = priority;
		this.commendCode = commendCode;
		this.status = status;
		this.originalPrice = originalPrice;
		this.price = price;
		this.price1 = price1;
		this.price2 = price2;
		this.price3 = price3;
		this.price4 = price4;
		this.price5 = price5;
		this.point = point;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.unit = unit;
		this.quantity = quantity;
		this.minimumBuy = minimumBuy;
		this.commodityOrderItems = commodityOrderItems;
		this.labelCommodities = labelCommodities;
		this.commodities = commodities;
		this.commodityPromotions = commodityPromotions;
		this.commodityPictures = commodityPictures;
		this.favoriteCommodities = favoriteCommodities;
		this.commodityDetails = commodityDetails;
		this.commodityComments = commodityComments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	public CommodityProvider getCommodityProvider() {
		return this.commodityProvider;
	}

	public void setCommodityProvider(CommodityProvider commodityProvider) {
		this.commodityProvider = commodityProvider;
	}

	public CommodityCategory getCommodityCategory() {
		return this.commodityCategory;
	}

	public void setCommodityCategory(CommodityCategory commodityCategory) {
		this.commodityCategory = commodityCategory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getStandard() {
		return this.standard;
	}

	public void setStandard(String standard) {
		this.standard = standard;
	}

	public String getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

	public BigDecimal getPriceQuantity() {
		return this.priceQuantity;
	}

	public void setPriceQuantity(BigDecimal priceQuantity) {
		this.priceQuantity = priceQuantity;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getCommendCode() {
		return this.commendCode;
	}

	public void setCommendCode(String commendCode) {
		this.commendCode = commendCode;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getOriginalPrice() {
		return this.originalPrice;
	}

	public void setOriginalPrice(BigDecimal originalPrice) {
		this.originalPrice = originalPrice;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getPrice1() {
		return this.price1;
	}

	public void setPrice1(BigDecimal price1) {
		this.price1 = price1;
	}

	public BigDecimal getPrice2() {
		return this.price2;
	}

	public void setPrice2(BigDecimal price2) {
		this.price2 = price2;
	}

	public BigDecimal getPrice3() {
		return this.price3;
	}

	public void setPrice3(BigDecimal price3) {
		this.price3 = price3;
	}

	public BigDecimal getPrice4() {
		return this.price4;
	}

	public void setPrice4(BigDecimal price4) {
		this.price4 = price4;
	}

	public BigDecimal getPrice5() {
		return this.price5;
	}

	public void setPrice5(BigDecimal price5) {
		this.price5 = price5;
	}

	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public Integer getMinimumBuy() {
		return this.minimumBuy;
	}

	public void setMinimumBuy(Integer minimumBuy) {
		this.minimumBuy = minimumBuy;
	}

	public Set<CommodityOrderItem> getCommodityOrderItems() {
		return this.commodityOrderItems;
	}

	public void setCommodityOrderItems(
			Set<CommodityOrderItem> commodityOrderItems) {
		this.commodityOrderItems = commodityOrderItems;
	}

	public Set<LabelCommodity> getLabelCommodities() {
		return this.labelCommodities;
	}

	public void setLabelCommodities(Set<LabelCommodity> labelCommodities) {
		this.labelCommodities = labelCommodities;
	}

	public Set<Commodity> getCommodities() {
		return this.commodities;
	}

	public void setCommodities(Set<Commodity> commodities) {
		this.commodities = commodities;
	}

	public Set<CommodityPromotion> getCommodityPromotions() {
		return this.commodityPromotions;
	}

	public void setCommodityPromotions(
			Set<CommodityPromotion> commodityPromotions) {
		this.commodityPromotions = commodityPromotions;
	}

	public Set<CommodityPicture> getCommodityPictures() {
		return this.commodityPictures;
	}

	public void setCommodityPictures(Set<CommodityPicture> commodityPictures) {
		this.commodityPictures = commodityPictures;
	}

	public Set<FavoriteCommodity> getFavoriteCommodities() {
		return this.favoriteCommodities;
	}

	public void setFavoriteCommodities(
			Set<FavoriteCommodity> favoriteCommodities) {
		this.favoriteCommodities = favoriteCommodities;
	}

	public Set<CommodityDetail> getCommodityDetails() {
		return this.commodityDetails;
	}

	public void setCommodityDetails(Set<CommodityDetail> commodityDetails) {
		this.commodityDetails = commodityDetails;
	}

	public Set<CommodityComment> getCommodityComments() {
		return this.commodityComments;
	}

	public void setCommodityComments(Set<CommodityComment> commodityComments) {
		this.commodityComments = commodityComments;
	}

}
