// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

/**
 * CommodityDetail generated by hbm2java
 */
public class CommodityDetail implements java.io.Serializable {

	private Integer id;
	private Commodity commodity;
	private String detailCode;
	private String introduction;
	private String remark;

	public CommodityDetail() {
	}

	public CommodityDetail(Commodity commodity, String detailCode,
			String introduction, String remark) {
		this.commodity = commodity;
		this.detailCode = detailCode;
		this.introduction = introduction;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	public String getDetailCode() {
		return this.detailCode;
	}

	public void setDetailCode(String detailCode) {
		this.detailCode = detailCode;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
