// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Content generated by hbm2java
 */
public class Content implements java.io.Serializable {

	private Integer id;
	private SiteModule siteModule;
	private CommodityCategory commodityCategory;
	private String positionCode;
	private String typeCode;
	private String title;
	private String picturePath;
	private String keyword;
	private String source;
	private String author;
	private String content;
	private Integer priority;
	private String status;
	private Integer updater;
	private Date updateTime;
	private String remark;
	private Set<FavoriteContent> favoriteContents = new HashSet<FavoriteContent>(
			0);
	private Set<LabelContent> labelContents = new HashSet<LabelContent>(0);

	public Content() {
	}

	public Content(String positionCode, String typeCode, Integer priority,
			String status, Date updateTime) {
		this.positionCode = positionCode;
		this.typeCode = typeCode;
		this.priority = priority;
		this.status = status;
		this.updateTime = updateTime;
	}

	public Content(SiteModule siteModule, CommodityCategory commodityCategory,
			String positionCode, String typeCode, String title,
			String picturePath, String keyword, String source, String author,
			String content, Integer priority, String status, Integer updater,
			Date updateTime, String remark,
			Set<FavoriteContent> favoriteContents,
			Set<LabelContent> labelContents) {
		this.siteModule = siteModule;
		this.commodityCategory = commodityCategory;
		this.positionCode = positionCode;
		this.typeCode = typeCode;
		this.title = title;
		this.picturePath = picturePath;
		this.keyword = keyword;
		this.source = source;
		this.author = author;
		this.content = content;
		this.priority = priority;
		this.status = status;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.favoriteContents = favoriteContents;
		this.labelContents = labelContents;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SiteModule getSiteModule() {
		return this.siteModule;
	}

	public void setSiteModule(SiteModule siteModule) {
		this.siteModule = siteModule;
	}

	public CommodityCategory getCommodityCategory() {
		return this.commodityCategory;
	}

	public void setCommodityCategory(CommodityCategory commodityCategory) {
		this.commodityCategory = commodityCategory;
	}

	public String getPositionCode() {
		return this.positionCode;
	}

	public void setPositionCode(String positionCode) {
		this.positionCode = positionCode;
	}

	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<FavoriteContent> getFavoriteContents() {
		return this.favoriteContents;
	}

	public void setFavoriteContents(Set<FavoriteContent> favoriteContents) {
		this.favoriteContents = favoriteContents;
	}

	public Set<LabelContent> getLabelContents() {
		return this.labelContents;
	}

	public void setLabelContents(Set<LabelContent> labelContents) {
		this.labelContents = labelContents;
	}

}
