// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

/**
 * DeliveryContact generated by hbm2java
 */
public class DeliveryContact implements java.io.Serializable {

	private Integer id;
	private User user;
	private Area area;
	private String address;
	private String contact;
	private String contactPhone;
	private String status;
	private String remark;

	public DeliveryContact() {
	}

	public DeliveryContact(User user) {
		this.user = user;
	}

	public DeliveryContact(User user, Area area, String address,
			String contact, String contactPhone, String status, String remark) {
		this.user = user;
		this.area = area;
		this.address = address;
		this.contact = contact;
		this.contactPhone = contactPhone;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
