// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FavoriteContent generated by hbm2java
 */
public class FavoriteContent implements java.io.Serializable {

	private FavoriteContentId id;
	private User user;
	private Content content;
	private Date updateTime;
	private String remark;

	public FavoriteContent() {
	}

	public FavoriteContent(FavoriteContentId id, User user, Content content,
			Date updateTime) {
		this.id = id;
		this.user = user;
		this.content = content;
		this.updateTime = updateTime;
	}

	public FavoriteContent(FavoriteContentId id, User user, Content content,
			Date updateTime, String remark) {
		this.id = id;
		this.user = user;
		this.content = content;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	public FavoriteContentId getId() {
		return this.id;
	}

	public void setId(FavoriteContentId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
