// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FavoriteCommodity generated by hbm2java
 */
public class FavoriteCommodity implements java.io.Serializable {

	private FavoriteCommodityId id;
	private User user;
	private Commodity commodity;
	private Date updateTime;
	private String remark;

	public FavoriteCommodity() {
	}

	public FavoriteCommodity(FavoriteCommodityId id, User user,
			Commodity commodity, Date updateTime) {
		this.id = id;
		this.user = user;
		this.commodity = commodity;
		this.updateTime = updateTime;
	}

	public FavoriteCommodity(FavoriteCommodityId id, User user,
			Commodity commodity, Date updateTime, String remark) {
		this.id = id;
		this.user = user;
		this.commodity = commodity;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	public FavoriteCommodityId getId() {
		return this.id;
	}

	public void setId(FavoriteCommodityId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
