// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

/**
 * LabelContentId generated by hbm2java
 */
public class LabelContentId implements java.io.Serializable {

	private String labelName;
	private Integer contentId;

	public LabelContentId() {
	}

	public LabelContentId(String labelName, Integer contentId) {
		this.labelName = labelName;
		this.contentId = contentId;
	}

	public String getLabelName() {
		return this.labelName;
	}

	public void setLabelName(String labelName) {
		this.labelName = labelName;
	}

	public Integer getContentId() {
		return this.contentId;
	}

	public void setContentId(Integer contentId) {
		this.contentId = contentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LabelContentId))
			return false;
		LabelContentId castOther = (LabelContentId) other;

		return ((this.getLabelName() == castOther.getLabelName()) || (this
				.getLabelName() != null && castOther.getLabelName() != null && this
				.getLabelName().equals(castOther.getLabelName())))
				&& ((this.getContentId() == castOther.getContentId()) || (this
						.getContentId() != null
						&& castOther.getContentId() != null && this
						.getContentId().equals(castOther.getContentId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLabelName() == null ? 0 : this.getLabelName().hashCode());
		result = 37 * result
				+ (getContentId() == null ? 0 : this.getContentId().hashCode());
		return result;
	}

}
