// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

/**
 * LabelContent generated by hbm2java
 */
public class LabelContent implements java.io.Serializable {

	private LabelContentId id;
	private Content content;
	private LabelWord labelWord;
	private String status;
	private String remark;

	public LabelContent() {
	}

	public LabelContent(LabelContentId id, Content content, LabelWord labelWord) {
		this.id = id;
		this.content = content;
		this.labelWord = labelWord;
	}

	public LabelContent(LabelContentId id, Content content,
			LabelWord labelWord, String status, String remark) {
		this.id = id;
		this.content = content;
		this.labelWord = labelWord;
		this.status = status;
		this.remark = remark;
	}

	public LabelContentId getId() {
		return this.id;
	}

	public void setId(LabelContentId id) {
		this.id = id;
	}

	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	public LabelWord getLabelWord() {
		return this.labelWord;
	}

	public void setLabelWord(LabelWord labelWord) {
		this.labelWord = labelWord;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
