// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

/**
 * LabelCommodityId generated by hbm2java
 */
public class LabelCommodityId implements java.io.Serializable {

	private String labelName;
	private Integer commodityId;

	public LabelCommodityId() {
	}

	public LabelCommodityId(String labelName, Integer commodityId) {
		this.labelName = labelName;
		this.commodityId = commodityId;
	}

	public String getLabelName() {
		return this.labelName;
	}

	public void setLabelName(String labelName) {
		this.labelName = labelName;
	}

	public Integer getCommodityId() {
		return this.commodityId;
	}

	public void setCommodityId(Integer commodityId) {
		this.commodityId = commodityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LabelCommodityId))
			return false;
		LabelCommodityId castOther = (LabelCommodityId) other;

		return ((this.getLabelName() == castOther.getLabelName()) || (this
				.getLabelName() != null && castOther.getLabelName() != null && this
				.getLabelName().equals(castOther.getLabelName())))
				&& ((this.getCommodityId() == castOther.getCommodityId()) || (this
						.getCommodityId() != null
						&& castOther.getCommodityId() != null && this
						.getCommodityId().equals(castOther.getCommodityId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLabelName() == null ? 0 : this.getLabelName().hashCode());
		result = 37
				* result
				+ (getCommodityId() == null ? 0 : this.getCommodityId()
						.hashCode());
		return result;
	}

}
