// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PointConsumeLog generated by hbm2java
 */
public class PointConsumeLog implements java.io.Serializable {

	private Integer id;
	private CommodityPayment commodityPayment;
	private BigDecimal point;
	private Date consumeTime;
	private String remark;

	public PointConsumeLog() {
	}

	public PointConsumeLog(CommodityPayment commodityPayment, BigDecimal point,
			Date consumeTime) {
		this.commodityPayment = commodityPayment;
		this.point = point;
		this.consumeTime = consumeTime;
	}

	public PointConsumeLog(CommodityPayment commodityPayment, BigDecimal point,
			Date consumeTime, String remark) {
		this.commodityPayment = commodityPayment;
		this.point = point;
		this.consumeTime = consumeTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CommodityPayment getCommodityPayment() {
		return this.commodityPayment;
	}

	public void setCommodityPayment(CommodityPayment commodityPayment) {
		this.commodityPayment = commodityPayment;
	}

	public BigDecimal getPoint() {
		return this.point;
	}

	public void setPoint(BigDecimal point) {
		this.point = point;
	}

	public Date getConsumeTime() {
		return this.consumeTime;
	}

	public void setConsumeTime(Date consumeTime) {
		this.consumeTime = consumeTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
