// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QuickComment generated by hbm2java
 */
public class QuickComment implements java.io.Serializable {

	private Integer id;
	private QuickComment quickComment;
	private Admin admin;
	private String clientName;
	private String commentContent;
	private Date commentTime;
	private String replyContent;
	private Date replyTime;
	private Integer commentLevel;
	private String status;
	private String remark;
	private Set<QuickComment> quickComments = new HashSet<QuickComment>(0);

	public QuickComment() {
	}

	public QuickComment(Date commentTime, Date replyTime) {
		this.commentTime = commentTime;
		this.replyTime = replyTime;
	}

	public QuickComment(QuickComment quickComment, Admin admin,
			String clientName, String commentContent, Date commentTime,
			String replyContent, Date replyTime, Integer commentLevel,
			String status, String remark, Set<QuickComment> quickComments) {
		this.quickComment = quickComment;
		this.admin = admin;
		this.clientName = clientName;
		this.commentContent = commentContent;
		this.commentTime = commentTime;
		this.replyContent = replyContent;
		this.replyTime = replyTime;
		this.commentLevel = commentLevel;
		this.status = status;
		this.remark = remark;
		this.quickComments = quickComments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public QuickComment getQuickComment() {
		return this.quickComment;
	}

	public void setQuickComment(QuickComment quickComment) {
		this.quickComment = quickComment;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	public Date getReplyTime() {
		return this.replyTime;
	}

	public void setReplyTime(Date replyTime) {
		this.replyTime = replyTime;
	}

	public Integer getCommentLevel() {
		return this.commentLevel;
	}

	public void setCommentLevel(Integer commentLevel) {
		this.commentLevel = commentLevel;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<QuickComment> getQuickComments() {
		return this.quickComments;
	}

	public void setQuickComments(Set<QuickComment> quickComments) {
		this.quickComments = quickComments;
	}

}
