// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SiteModule generated by hbm2java
 */
public class SiteModule implements java.io.Serializable {

	private Integer id;
	private SiteModule siteModule;
	private PageTemplate pageTemplate;
	private String name;
	private String code;
	private String type;
	private String url;
	private String queryString;
	private String title;
	private String subtitle;
	private Integer updater;
	private Date updateTime;
	private Integer priority;
	private String status;
	private String remark;
	private Set<Content> contents = new HashSet<Content>(0);
	private Set<SiteModule> siteModules = new HashSet<SiteModule>(0);
	private Set<Survey> surveies = new HashSet<Survey>(0);

	public SiteModule() {
	}

	public SiteModule(Date updateTime) {
		this.updateTime = updateTime;
	}

	public SiteModule(SiteModule siteModule, PageTemplate pageTemplate,
			String name, String code, String type, String url,
			String queryString, String title, String subtitle, Integer updater,
			Date updateTime, Integer priority, String status, String remark,
			Set<Content> contents, Set<SiteModule> siteModules,
			Set<Survey> surveies) {
		this.siteModule = siteModule;
		this.pageTemplate = pageTemplate;
		this.name = name;
		this.code = code;
		this.type = type;
		this.url = url;
		this.queryString = queryString;
		this.title = title;
		this.subtitle = subtitle;
		this.updater = updater;
		this.updateTime = updateTime;
		this.priority = priority;
		this.status = status;
		this.remark = remark;
		this.contents = contents;
		this.siteModules = siteModules;
		this.surveies = surveies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SiteModule getSiteModule() {
		return this.siteModule;
	}

	public void setSiteModule(SiteModule siteModule) {
		this.siteModule = siteModule;
	}

	public PageTemplate getPageTemplate() {
		return this.pageTemplate;
	}

	public void setPageTemplate(PageTemplate pageTemplate) {
		this.pageTemplate = pageTemplate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getQueryString() {
		return this.queryString;
	}

	public void setQueryString(String queryString) {
		this.queryString = queryString;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubtitle() {
		return this.subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Content> getContents() {
		return this.contents;
	}

	public void setContents(Set<Content> contents) {
		this.contents = contents;
	}

	public Set<SiteModule> getSiteModules() {
		return this.siteModules;
	}

	public void setSiteModules(Set<SiteModule> siteModules) {
		this.siteModules = siteModules;
	}

	public Set<Survey> getSurveies() {
		return this.surveies;
	}

	public void setSurveies(Set<Survey> surveies) {
		this.surveies = surveies;
	}

}
