// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SmsContact generated by hbm2java
 */
public class SmsContact implements java.io.Serializable {

	private Integer id;
	private String phoneNumber;
	private String contact;
	private Integer groupId;
	private Integer updater;
	private Date updateTime;
	private String status;
	private String remark;

	public SmsContact() {
	}

	public SmsContact(String phoneNumber, Integer groupId, Date updateTime) {
		this.phoneNumber = phoneNumber;
		this.groupId = groupId;
		this.updateTime = updateTime;
	}

	public SmsContact(String phoneNumber, String contact, Integer groupId,
			Integer updater, Date updateTime, String status, String remark) {
		this.phoneNumber = phoneNumber;
		this.contact = contact;
		this.groupId = groupId;
		this.updater = updater;
		this.updateTime = updateTime;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
