// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SmsGroup generated by hbm2java
 */
public class SmsGroup implements java.io.Serializable {

	private Integer id;
	private String groupName;
	private Integer updater;
	private Date updateTime;
	private String status;
	private String remark;

	public SmsGroup() {
	}

	public SmsGroup(String groupName, Date updateTime) {
		this.groupName = groupName;
		this.updateTime = updateTime;
	}

	public SmsGroup(String groupName, Integer updater, Date updateTime,
			String status, String remark) {
		this.groupName = groupName;
		this.updater = updater;
		this.updateTime = updateTime;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
