// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Survey generated by hbm2java
 */
public class Survey implements java.io.Serializable {

	private Integer id;
	private SiteModule siteModule;
	private String groupCode;
	private String surveyCode;
	private String typeCode;
	private String title;
	private String description;
	private Date startTime;
	private Date endTime;
	private Integer count;
	private String remark;
	private Set<SurveyItem> surveyItems = new HashSet<SurveyItem>(0);

	public Survey() {
	}

	public Survey(Integer id, String surveyCode, String typeCode, String title,
			Date startTime, Date endTime) {
		this.id = id;
		this.surveyCode = surveyCode;
		this.typeCode = typeCode;
		this.title = title;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public Survey(Integer id, SiteModule siteModule, String groupCode,
			String surveyCode, String typeCode, String title,
			String description, Date startTime, Date endTime, Integer count,
			String remark, Set<SurveyItem> surveyItems) {
		this.id = id;
		this.siteModule = siteModule;
		this.groupCode = groupCode;
		this.surveyCode = surveyCode;
		this.typeCode = typeCode;
		this.title = title;
		this.description = description;
		this.startTime = startTime;
		this.endTime = endTime;
		this.count = count;
		this.remark = remark;
		this.surveyItems = surveyItems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SiteModule getSiteModule() {
		return this.siteModule;
	}

	public void setSiteModule(SiteModule siteModule) {
		this.siteModule = siteModule;
	}

	public String getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	public String getSurveyCode() {
		return this.surveyCode;
	}

	public void setSurveyCode(String surveyCode) {
		this.surveyCode = surveyCode;
	}

	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<SurveyItem> getSurveyItems() {
		return this.surveyItems;
	}

	public void setSurveyItems(Set<SurveyItem> surveyItems) {
		this.surveyItems = surveyItems;
	}

}
