// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserMaintainLog generated by hbm2java
 */
public class UserMaintainLog implements java.io.Serializable {

	private Integer id;
	private User user;
	private Admin adminByAdminId;
	private Admin adminByUpdater;
	private Date maintainTime;
	private String summary;
	private String detail;
	private Date updateTime;
	private String remark;

	public UserMaintainLog() {
	}

	public UserMaintainLog(Date maintainTime, Date updateTime) {
		this.maintainTime = maintainTime;
		this.updateTime = updateTime;
	}

	public UserMaintainLog(User user, Admin adminByAdminId,
			Admin adminByUpdater, Date maintainTime, String summary,
			String detail, Date updateTime, String remark) {
		this.user = user;
		this.adminByAdminId = adminByAdminId;
		this.adminByUpdater = adminByUpdater;
		this.maintainTime = maintainTime;
		this.summary = summary;
		this.detail = detail;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Admin getAdminByAdminId() {
		return this.adminByAdminId;
	}

	public void setAdminByAdminId(Admin adminByAdminId) {
		this.adminByAdminId = adminByAdminId;
	}

	public Admin getAdminByUpdater() {
		return this.adminByUpdater;
	}

	public void setAdminByUpdater(Admin adminByUpdater) {
		this.adminByUpdater = adminByUpdater;
	}

	public Date getMaintainTime() {
		return this.maintainTime;
	}

	public void setMaintainTime(Date maintainTime) {
		this.maintainTime = maintainTime;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
