// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private Area area;
	private User user;
	private Admin admin;
	private String name;
	private String password;
	private String fullName;
	private String userType;
	private String contact;
	private String website;
	private String fax;
	private Date lastMaintainTime;
	private String sinaAuthorization;
	private String qqAuthorization;
	private Integer age;
	private String sex;
	private String email;
	private String phone;
	private String mobile;
	private String credentialType;
	private String credentialNumber;
	private BigDecimal point;
	private BigDecimal empiricValue;
	private Integer level;
	private String address;
	private String status;
	private String picturePath;
	private Date registerTime;
	private Integer updater;
	private Date updateTime;
	private String remark;
	private Integer parentUserId;
	private Set<QuickOrder> quickOrders = new HashSet<QuickOrder>(0);
	private UserDetail userDetail;
	private Set<FavoriteCommodity> favoriteCommodities = new HashSet<FavoriteCommodity>(
			0);
	private Set<UserContract> userContracts = new HashSet<UserContract>(0);
	private Set<FavoriteContent> favoriteContents = new HashSet<FavoriteContent>(
			0);
	private Set<User> users = new HashSet<User>(0);
	private Set<PointLog> pointLogs = new HashSet<PointLog>(0);
	private Set<UserMaintainLog> userMaintainLogs = new HashSet<UserMaintainLog>(
			0);
	private Set<CommodityOrder> commodityOrders = new HashSet<CommodityOrder>(0);
	private Set<CommodityComment> commodityComments = new HashSet<CommodityComment>(
			0);
	private Set<DeliveryContact> deliveryContacts = new HashSet<DeliveryContact>(
			0);

	public User() {
	}

	public User(String name, String password, Date lastMaintainTime,
			String email, String status, Date registerTime, Date updateTime) {
		this.name = name;
		this.password = password;
		this.lastMaintainTime = lastMaintainTime;
		this.email = email;
		this.status = status;
		this.registerTime = registerTime;
		this.updateTime = updateTime;
	}

	public User(Area area, User user, Admin admin, String name,
			String password, String fullName, String userType, String contact,
			String website, String fax, Date lastMaintainTime,
			String sinaAuthorization, String qqAuthorization, Integer age,
			String sex, String email, String phone, String mobile,
			String credentialType, String credentialNumber, BigDecimal point,
			BigDecimal empiricValue, Integer level, String address,
			String status, String picturePath, Date registerTime,
			Integer updater, Date updateTime, String remark,
			Integer parentUserId, Set<QuickOrder> quickOrders,
			UserDetail userDetail, Set<FavoriteCommodity> favoriteCommodities,
			Set<UserContract> userContracts,
			Set<FavoriteContent> favoriteContents, Set<User> users,
			Set<PointLog> pointLogs, Set<UserMaintainLog> userMaintainLogs,
			Set<CommodityOrder> commodityOrders,
			Set<CommodityComment> commodityComments,
			Set<DeliveryContact> deliveryContacts) {
		this.area = area;
		this.user = user;
		this.admin = admin;
		this.name = name;
		this.password = password;
		this.fullName = fullName;
		this.userType = userType;
		this.contact = contact;
		this.website = website;
		this.fax = fax;
		this.lastMaintainTime = lastMaintainTime;
		this.sinaAuthorization = sinaAuthorization;
		this.qqAuthorization = qqAuthorization;
		this.age = age;
		this.sex = sex;
		this.email = email;
		this.phone = phone;
		this.mobile = mobile;
		this.credentialType = credentialType;
		this.credentialNumber = credentialNumber;
		this.point = point;
		this.empiricValue = empiricValue;
		this.level = level;
		this.address = address;
		this.status = status;
		this.picturePath = picturePath;
		this.registerTime = registerTime;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.parentUserId = parentUserId;
		this.quickOrders = quickOrders;
		this.userDetail = userDetail;
		this.favoriteCommodities = favoriteCommodities;
		this.userContracts = userContracts;
		this.favoriteContents = favoriteContents;
		this.users = users;
		this.pointLogs = pointLogs;
		this.userMaintainLogs = userMaintainLogs;
		this.commodityOrders = commodityOrders;
		this.commodityComments = commodityComments;
		this.deliveryContacts = deliveryContacts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Date getLastMaintainTime() {
		return this.lastMaintainTime;
	}

	public void setLastMaintainTime(Date lastMaintainTime) {
		this.lastMaintainTime = lastMaintainTime;
	}

	public String getSinaAuthorization() {
		return this.sinaAuthorization;
	}

	public void setSinaAuthorization(String sinaAuthorization) {
		this.sinaAuthorization = sinaAuthorization;
	}

	public String getQqAuthorization() {
		return this.qqAuthorization;
	}

	public void setQqAuthorization(String qqAuthorization) {
		this.qqAuthorization = qqAuthorization;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getCredentialType() {
		return this.credentialType;
	}

	public void setCredentialType(String credentialType) {
		this.credentialType = credentialType;
	}

	public String getCredentialNumber() {
		return this.credentialNumber;
	}

	public void setCredentialNumber(String credentialNumber) {
		this.credentialNumber = credentialNumber;
	}

	public BigDecimal getPoint() {
		return this.point;
	}

	public void setPoint(BigDecimal point) {
		this.point = point;
	}

	public BigDecimal getEmpiricValue() {
		return this.empiricValue;
	}

	public void setEmpiricValue(BigDecimal empiricValue) {
		this.empiricValue = empiricValue;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getParentUserId() {
		return this.parentUserId;
	}

	public void setParentUserId(Integer parentUserId) {
		this.parentUserId = parentUserId;
	}

	public Set<QuickOrder> getQuickOrders() {
		return this.quickOrders;
	}

	public void setQuickOrders(Set<QuickOrder> quickOrders) {
		this.quickOrders = quickOrders;
	}

	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public Set<FavoriteCommodity> getFavoriteCommodities() {
		return this.favoriteCommodities;
	}

	public void setFavoriteCommodities(
			Set<FavoriteCommodity> favoriteCommodities) {
		this.favoriteCommodities = favoriteCommodities;
	}

	public Set<UserContract> getUserContracts() {
		return this.userContracts;
	}

	public void setUserContracts(Set<UserContract> userContracts) {
		this.userContracts = userContracts;
	}

	public Set<FavoriteContent> getFavoriteContents() {
		return this.favoriteContents;
	}

	public void setFavoriteContents(Set<FavoriteContent> favoriteContents) {
		this.favoriteContents = favoriteContents;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<PointLog> getPointLogs() {
		return this.pointLogs;
	}

	public void setPointLogs(Set<PointLog> pointLogs) {
		this.pointLogs = pointLogs;
	}

	public Set<UserMaintainLog> getUserMaintainLogs() {
		return this.userMaintainLogs;
	}

	public void setUserMaintainLogs(Set<UserMaintainLog> userMaintainLogs) {
		this.userMaintainLogs = userMaintainLogs;
	}

	public Set<CommodityOrder> getCommodityOrders() {
		return this.commodityOrders;
	}

	public void setCommodityOrders(Set<CommodityOrder> commodityOrders) {
		this.commodityOrders = commodityOrders;
	}

	public Set<CommodityComment> getCommodityComments() {
		return this.commodityComments;
	}

	public void setCommodityComments(Set<CommodityComment> commodityComments) {
		this.commodityComments = commodityComments;
	}

	public Set<DeliveryContact> getDeliveryContacts() {
		return this.deliveryContacts;
	}

	public void setDeliveryContacts(Set<DeliveryContact> deliveryContacts) {
		this.deliveryContacts = deliveryContacts;
	}

}
