// default package
// Generated Jul 9, 2013 11:44:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserContract generated by hbm2java
 */
public class UserContract implements java.io.Serializable {

	private Integer id;
	private User user;
	private Admin admin;
	private String contractType;
	private Date startTime;
	private Date endTime;
	private String contractContent;
	private String contractFile;
	private Date signTime;
	private String status;
	private String remark;

	public UserContract() {
	}

	public UserContract(User user, String contractType, Date startTime,
			Date endTime, Date signTime) {
		this.user = user;
		this.contractType = contractType;
		this.startTime = startTime;
		this.endTime = endTime;
		this.signTime = signTime;
	}

	public UserContract(User user, Admin admin, String contractType,
			Date startTime, Date endTime, String contractContent,
			String contractFile, Date signTime, String status, String remark) {
		this.user = user;
		this.admin = admin;
		this.contractType = contractType;
		this.startTime = startTime;
		this.endTime = endTime;
		this.contractContent = contractContent;
		this.contractFile = contractFile;
		this.signTime = signTime;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getContractType() {
		return this.contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getContractContent() {
		return this.contractContent;
	}

	public void setContractContent(String contractContent) {
		this.contractContent = contractContent;
	}

	public String getContractFile() {
		return this.contractFile;
	}

	public void setContractFile(String contractFile) {
		this.contractFile = contractFile;
	}

	public Date getSignTime() {
		return this.signTime;
	}

	public void setSignTime(Date signTime) {
		this.signTime = signTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
