package com.runtech.onlineshop.model;
// Generated 2016-4-30 21:40:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CommodityCategory generated by hbm2java
 */
public class CommodityCategory implements java.io.Serializable {

	private Integer id;
	private Integer parentId;
	private String name;
	private String description;
	private String status;
	private Integer updater;
	private Date updateTime;
	private Integer priority;
	private String remark;

	public CommodityCategory() {
	}

	public CommodityCategory(String name, String status, Date updateTime) {
		this.name = name;
		this.status = status;
		this.updateTime = updateTime;
	}

	public CommodityCategory( String name, String description, String status,
			Integer updater, Date updateTime, Integer priority, String remark) {
		this.name = name;
		this.description = description;
		this.status = status;
		this.updater = updater;
		this.updateTime = updateTime;
		this.priority = priority;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
