package com.runtech.onlineshop.model;
// Generated 2016-5-5 11:32:02 by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CommodityProvider generated by hbm2java
 */
public class CommodityProvider implements java.io.Serializable {

	private Integer id;
	private Admin admin;
	private String name;
	private String type;
	private String supplyScope;
	private String phone;
	private String linkman;
	private String linkmanPhone;
	private String linkmanMobile;
	private String address;
	private String webSite;
	private String qq;
	private String email;
	private String description;
	private String registerNo;
	private String taxNo;
	private String organizationNo;
	private String contractContent;
	private String contractFileName;
	private Blob contractFile;
	private Date updateTime;
	private String status;
	private String remark;

	public CommodityProvider() {
	}

	public CommodityProvider(String name, Date updateTime) {
		this.name = name;
		this.updateTime = updateTime;
	}

	public CommodityProvider(Admin admin, String name, String type, String supplyScope, String phone, String linkman,
			String linkmanPhone, String linkmanMobile, String address, String webSite, String qq, String email,
			String description, String registerNo, String taxNo, String organizationNo, String contractContent,
			String contractFileName, Blob contractFile, Date updateTime, String status, String remark
			) {
		this.admin = admin;
		this.name = name;
		this.type = type;
		this.supplyScope = supplyScope;
		this.phone = phone;
		this.linkman = linkman;
		this.linkmanPhone = linkmanPhone;
		this.linkmanMobile = linkmanMobile;
		this.address = address;
		this.webSite = webSite;
		this.qq = qq;
		this.email = email;
		this.description = description;
		this.registerNo = registerNo;
		this.taxNo = taxNo;
		this.organizationNo = organizationNo;
		this.contractContent = contractContent;
		this.contractFileName = contractFileName;
		this.contractFile = contractFile;
		this.updateTime = updateTime;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSupplyScope() {
		return this.supplyScope;
	}

	public void setSupplyScope(String supplyScope) {
		this.supplyScope = supplyScope;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinkmanPhone() {
		return this.linkmanPhone;
	}

	public void setLinkmanPhone(String linkmanPhone) {
		this.linkmanPhone = linkmanPhone;
	}

	public String getLinkmanMobile() {
		return this.linkmanMobile;
	}

	public void setLinkmanMobile(String linkmanMobile) {
		this.linkmanMobile = linkmanMobile;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getWebSite() {
		return this.webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRegisterNo() {
		return this.registerNo;
	}

	public void setRegisterNo(String registerNo) {
		this.registerNo = registerNo;
	}

	public String getTaxNo() {
		return this.taxNo;
	}

	public void setTaxNo(String taxNo) {
		this.taxNo = taxNo;
	}

	public String getOrganizationNo() {
		return this.organizationNo;
	}

	public void setOrganizationNo(String organizationNo) {
		this.organizationNo = organizationNo;
	}

	public String getContractContent() {
		return this.contractContent;
	}

	public void setContractContent(String contractContent) {
		this.contractContent = contractContent;
	}

	public String getContractFileName() {
		return this.contractFileName;
	}

	public void setContractFileName(String contractFileName) {
		this.contractFileName = contractFileName;
	}

	public Blob getContractFile() {
		return this.contractFile;
	}

	public void setContractFile(Blob blob) {
		this.contractFile = blob;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}


}
