package com.runtech.onlineshop.model;
// Generated 2016-5-5 11:54:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consignment generated by hbm2java
 */
public class Consignment implements java.io.Serializable {

	private Integer id;
	private CommodityProvider deliveryCompany;
	private CommodityProvider company;
	private String title;
	private String description;
	private String operator;
	private String position;
	private Date createTime;
	private Date deliveryTime;
	private String status;
	private String comment;
	private Set<CommodityOrder> commodityOrders = new HashSet<CommodityOrder>(0);
	private Set<ConsignmentPicture> consignmentPictures = new HashSet<ConsignmentPicture>(0);

	public Consignment() {
	}

	public Consignment(Date createTime) {
		this.createTime = createTime;
	}

	public Consignment(CommodityProvider commodityProviderByDeliveryCompany,
			CommodityProvider commodityProviderByCompany, String title, String description, String operator,
			String position, Date createTime, Date deliveryTime, String status, String comment,
			Set<CommodityOrder> commodityOrders,Set<ConsignmentPicture> consignmentPictures) {
		this.deliveryCompany = commodityProviderByDeliveryCompany;
		this.company = commodityProviderByCompany;
		this.title = title;
		this.description = description;
		this.operator = operator;
		this.position = position;
		this.createTime = createTime;
		this.deliveryTime = deliveryTime;
		this.status = status;
		this.comment = comment;
		this.consignmentPictures = consignmentPictures;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public CommodityProvider getDeliveryCompany() {
		return deliveryCompany;
	}

	public void setDeliveryCompany(CommodityProvider deliveryCompany) {
		this.deliveryCompany = deliveryCompany;
	}

	public CommodityProvider getCompany() {
		return company;
	}

	public void setCompany(CommodityProvider company) {
		this.company = company;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}


	public Set<ConsignmentPicture> getConsignmentPictures() {
		return this.consignmentPictures;
	}

	public void setConsignmentPictures(Set<ConsignmentPicture> consignmentPictures) {
		this.consignmentPictures = consignmentPictures;
	}

	public Set<CommodityOrder> getCommodityOrders() {
		return commodityOrders;
	}

	public void setCommodityOrders(Set<CommodityOrder> commodityOrders) {
		this.commodityOrders = commodityOrders;
	}

}
