package com.runtech.onlineshop.model;
// Generated 2016-5-5 11:54:37 by Hibernate Tools 3.4.0.CR1

/**
 * ConsignmentPicture generated by hbm2java
 */
public class ConsignmentPicture implements java.io.Serializable {

	private Integer id;
	private Consignment consignment;
	private String picturePath;
	private String pictureName;
	private String pictureDescription;
	private String picturePosition;

	public ConsignmentPicture() {
	}

	public ConsignmentPicture(Consignment consignment) {
		this.consignment = consignment;
	}

	public ConsignmentPicture(Consignment consignment, String picturePath, String pictureName,
			String pictureDescription, String picturePosition) {
		this.consignment = consignment;
		this.picturePath = picturePath;
		this.pictureName = pictureName;
		this.pictureDescription = pictureDescription;
		this.picturePosition = picturePosition;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Consignment getConsignment() {
		return this.consignment;
	}

	public void setConsignment(Consignment consignment) {
		this.consignment = consignment;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public String getPictureName() {
		return this.pictureName;
	}

	public void setPictureName(String pictureName) {
		this.pictureName = pictureName;
	}

	public String getPictureDescription() {
		return this.pictureDescription;
	}

	public void setPictureDescription(String pictureDescription) {
		this.pictureDescription = pictureDescription;
	}

	public String getPicturePosition() {
		return this.picturePosition;
	}

	public void setPicturePosition(String picturePosition) {
		this.picturePosition = picturePosition;
	}

}
