
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LinkWSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LinkWSSoap {


    /**
     * 
     * @param content
     * @param pwd
     * @param cell
     * @param sendTime
     * @param corpID
     * @param mobile
     * @return
     *     returns int
     */
    @WebMethod(operationName = "BatchSend", action = "http://tempuri.org/BatchSend")
    @WebResult(name = "BatchSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchSend", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BatchSend")
    @ResponseWrapper(localName = "BatchSendResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BatchSendResponse")
    public int batchSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param corpName
     * @param pwd
     * @param memo
     * @param email
     * @param linkMan
     * @param tel
     * @param corpID
     * @param mobile
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Reg", action = "http://tempuri.org/Reg")
    @WebResult(name = "RegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Reg", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Reg")
    @ResponseWrapper(localName = "RegResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegResponse")
    public int reg(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "CorpName", targetNamespace = "http://tempuri.org/")
        String corpName,
        @WebParam(name = "LinkMan", targetNamespace = "http://tempuri.org/")
        String linkMan,
        @WebParam(name = "Tel", targetNamespace = "http://tempuri.org/")
        String tel,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "Memo", targetNamespace = "http://tempuri.org/")
        String memo);

    /**
     * 
     * @param newPwd
     * @param pwd
     * @param corpID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdPwd", action = "http://tempuri.org/UpdPwd")
    @WebResult(name = "UpdPwdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdPwd", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdPwd")
    @ResponseWrapper(localName = "UpdPwdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdPwdResponse")
    public int updPwd(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "NewPwd", targetNamespace = "http://tempuri.org/")
        String newPwd);

    /**
     * 
     * @param corpName
     * @param pwd
     * @param memo
     * @param email
     * @param linkMan
     * @param tel
     * @param corpID
     * @param mobile
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdReg", action = "http://tempuri.org/UpdReg")
    @WebResult(name = "UpdRegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdReg", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdReg")
    @ResponseWrapper(localName = "UpdRegResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdRegResponse")
    public int updReg(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "CorpName", targetNamespace = "http://tempuri.org/")
        String corpName,
        @WebParam(name = "LinkMan", targetNamespace = "http://tempuri.org/")
        String linkMan,
        @WebParam(name = "Tel", targetNamespace = "http://tempuri.org/")
        String tel,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "Memo", targetNamespace = "http://tempuri.org/")
        String memo);

    /**
     * 
     * @param pwd
     * @param corpID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SelSum", action = "http://tempuri.org/SelSum")
    @WebResult(name = "SelSumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SelSum", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelSum")
    @ResponseWrapper(localName = "SelSumResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelSumResponse")
    public int selSum(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param content
     * @param pwd
     * @param cell
     * @param sendTime
     * @param corpID
     * @param mobile
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Send", action = "http://tempuri.org/Send")
    @WebResult(name = "SendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Send", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Send")
    @ResponseWrapper(localName = "SendResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendResponse")
    public int send(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param pwd
     * @param corpID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get", action = "http://tempuri.org/Get")
    @WebResult(name = "GetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Get")
    @ResponseWrapper(localName = "GetResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetResponse")
    public String get(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param pwd
     * @param corpID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UnReg", action = "http://tempuri.org/UnReg")
    @WebResult(name = "UnRegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UnReg", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnReg")
    @ResponseWrapper(localName = "UnRegResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnRegResponse")
    public int unReg(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param cardNo
     * @param cardPwd
     * @param pwd
     * @param corpID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ChargeUp", action = "http://tempuri.org/ChargeUp")
    @WebResult(name = "ChargeUpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChargeUp", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChargeUp")
    @ResponseWrapper(localName = "ChargeUpResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChargeUpResponse")
    public int chargeUp(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "CardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "CardPwd", targetNamespace = "http://tempuri.org/")
        String cardPwd);

    /**
     * 
     * @param pwd
     * @param corpID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ShowMessage", action = "http://tempuri.org/ShowMessage")
    @WebResult(name = "ShowMessageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ShowMessage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ShowMessage")
    @ResponseWrapper(localName = "ShowMessageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ShowMessageResponse")
    public String showMessage(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * ȡ�ø��°汾
     * 
     * @param ver
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVer", action = "http://tempuri.org/GetVer")
    @WebResult(name = "GetVerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVer")
    @ResponseWrapper(localName = "GetVerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVerResponse")
    public String getVer(
        @WebParam(name = "Ver", targetNamespace = "http://tempuri.org/")
        String ver);

    /**
     * ���߸������
     * 
     * @param ver
     * @return
     *     returns org.tempuri.GetUpdateDataResponse.GetUpdateDataResult
     */
    @WebMethod(operationName = "GetUpdateData", action = "http://tempuri.org/GetUpdateData")
    @WebResult(name = "GetUpdateDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUpdateData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUpdateData")
    @ResponseWrapper(localName = "GetUpdateDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUpdateDataResponse")
    public org.tempuri.GetUpdateDataResponse.GetUpdateDataResult getUpdateData(
        @WebParam(name = "Ver", targetNamespace = "http://tempuri.org/")
        String ver);

}
