package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdminModule generated by hbm2java
 */
public class AdminModule implements java.io.Serializable {

	private Integer id;
	private AdminModule adminModule;
	private String name;
	private String code;
	private String page;
	private String title;
	private String subtitle;
	private String modelType;
	private String isSystemModule;
	private boolean isHidden;
	private Integer priority;
	private Integer updater;
	private Date updateTime;
	private String remark;
	private Set<AdminModule> adminModules = new HashSet<AdminModule>(0);
	private Set<AdminRoleModule> adminRoleModules = new HashSet<AdminRoleModule>(
			0);

	public AdminModule() {
	}

	public AdminModule(String name, String code, boolean isHidden,
			Date updateTime) {
		this.name = name;
		this.code = code;
		this.isHidden = isHidden;
		this.updateTime = updateTime;
	}

	public AdminModule(AdminModule adminModule, String name, String code,
			String page, String title, String subtitle, String modelType,
			String isSystemModule, boolean isHidden, Integer priority,
			Integer updater, Date updateTime, String remark,
			Set<AdminModule> adminModules, Set<AdminRoleModule> adminRoleModules) {
		this.adminModule = adminModule;
		this.name = name;
		this.code = code;
		this.page = page;
		this.title = title;
		this.subtitle = subtitle;
		this.modelType = modelType;
		this.isSystemModule = isSystemModule;
		this.isHidden = isHidden;
		this.priority = priority;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.adminModules = adminModules;
		this.adminRoleModules = adminRoleModules;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AdminModule getAdminModule() {
		return this.adminModule;
	}

	public void setAdminModule(AdminModule adminModule) {
		this.adminModule = adminModule;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubtitle() {
		return this.subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public String getModelType() {
		return this.modelType;
	}

	public void setModelType(String modelType) {
		this.modelType = modelType;
	}

	public String getIsSystemModule() {
		return this.isSystemModule;
	}

	public void setIsSystemModule(String isSystemModule) {
		this.isSystemModule = isSystemModule;
	}

	public boolean isIsHidden() {
		return this.isHidden;
	}

	public void setIsHidden(boolean isHidden) {
		this.isHidden = isHidden;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<AdminModule> getAdminModules() {
		return this.adminModules;
	}

	public void setAdminModules(Set<AdminModule> adminModules) {
		this.adminModules = adminModules;
	}

	public Set<AdminRoleModule> getAdminRoleModules() {
		return this.adminRoleModules;
	}

	public void setAdminRoleModules(Set<AdminRoleModule> adminRoleModules) {
		this.adminRoleModules = adminRoleModules;
	}

}
