package com.runtech.onlineshop.model;

// Generated Jul 22, 2013 8:33:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdminLoginLog generated by hbm2java
 */
public class AdminLoginLog implements java.io.Serializable {

	private Integer id;
	private Admin admin;
	private String loginMachine;
	private String loginFrom;
	private Boolean loginResult;
	private Date loginTime;

	public AdminLoginLog() {
	}

	public AdminLoginLog(Integer id, Admin admin, boolean loginResult,
			Date loginTime) {
		this.id = id;
		this.admin = admin;
		this.loginResult = loginResult;
		this.loginTime = loginTime;
	}

	public AdminLoginLog(Integer id, Admin admin, String loginMachine,
			String loginFrom, boolean loginResult, Date loginTime) {
		this.id = id;
		this.admin = admin;
		this.loginMachine = loginMachine;
		this.loginFrom = loginFrom;
		this.loginResult = loginResult;
		this.loginTime = loginTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getLoginMachine() {
		return this.loginMachine;
	}

	public void setLoginMachine(String loginMachine) {
		this.loginMachine = loginMachine;
	}

	public String getLoginFrom() {
		return this.loginFrom;
	}

	public void setLoginFrom(String loginFrom) {
		this.loginFrom = loginFrom;
	}

	public Boolean getLoginResult() {
		return this.loginResult;
	}

	public void setLoginResult(Boolean loginResult) {
		this.loginResult = loginResult;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

}
