package com.runtech.onlineshop.model;

// Generated Sep 18, 2011 10:02:44 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private Integer id;
	private Area area;
	private String code;
	private String name;
	private String category;
	private Integer priority;
	private Integer updater;
	private Date updateTime;
	private String status;
	private String remark;
	private Set quickOrders = new HashSet(0);
	private Set commodities = new HashSet(0);
	private Set users = new HashSet(0);
	private Set organizationUsers = new HashSet(0);
	private Set individualUsers = new HashSet(0);
	private Set deliveryContacts = new HashSet(0);
	private Set areas = new HashSet(0);
	private Set commodityOrders = new HashSet(0);

	public Area() {
	}

	public Area(String code, String name, String category, Integer priority,
			Date updateTime) {
		this.code = code;
		this.name = name;
		this.category = category;
		this.priority = priority;
		this.updateTime = updateTime;
	}

	public Area(Area area, String code, String name, String category,
			Integer priority, Integer updater, Date updateTime, String status,
			String remark, Set quickOrders, Set commodities, Set users,
			Set deliveryContacts, Set areas, Set commodityOrders) {
		this.area = area;
		this.code = code;
		this.name = name;
		this.category = category;
		this.priority = priority;
		this.updater = updater;
		this.updateTime = updateTime;
		this.status = status;
		this.remark = remark;
		this.quickOrders = quickOrders;
		this.commodities = commodities;
		this.users = users;
		this.deliveryContacts = deliveryContacts;
		this.areas = areas;
		this.commodityOrders = commodityOrders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getQuickOrders() {
		return this.quickOrders;
	}

	public void setQuickOrders(Set quickOrders) {
		this.quickOrders = quickOrders;
	}

	public Set getCommodities() {
		return this.commodities;
	}

	public void setCommodities(Set commodities) {
		this.commodities = commodities;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	public Set getOrganizationUsers() {
		return organizationUsers;
	}

	public void setOrganizationUsers(Set organizationUsers) {
		this.organizationUsers = organizationUsers;
	}

	public Set getIndividualUsers() {
		return individualUsers;
	}

	public void setIndividualUsers(Set individualUsers) {
		this.individualUsers = individualUsers;
	}

	public Set getDeliveryContacts() {
		return this.deliveryContacts;
	}

	public void setDeliveryContacts(Set deliveryContacts) {
		this.deliveryContacts = deliveryContacts;
	}

	public Set getAreas() {
		return this.areas;
	}

	public void setAreas(Set areas) {
		this.areas = areas;
	}

	public Set getCommodityOrders() {
		return this.commodityOrders;
	}

	public void setCommodityOrders(Set commodityOrders) {
		this.commodityOrders = commodityOrders;
	}

}
