package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

/**
 * BillCommodityOrder generated by hbm2java
 */
public class BillCommodityOrder implements java.io.Serializable {

	private Integer id;
	private Bill bill;
	private CommodityOrder commodityOrder;
	private String remark;

	public BillCommodityOrder() {
	}

	public BillCommodityOrder(Bill bill, CommodityOrder commodityOrder) {
		this.bill = bill;
		this.commodityOrder = commodityOrder;
	}

	public BillCommodityOrder(Bill bill, CommodityOrder commodityOrder, String remark) {
		this.bill = bill;
		this.commodityOrder = commodityOrder;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	public CommodityOrder getCommodityOrder() {
		return this.commodityOrder;
	}

	public void setCommodityOrder(CommodityOrder commodityOrder) {
		this.commodityOrder = commodityOrder;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
