package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

/**
 * CommodityDetail generated by hbm2java
 */
public class CommodityDetail implements java.io.Serializable {

	private Integer id;
	private CommodityBase commodityBase;
	private String detailCode;
	private String introduction;
	private String remark;

	public CommodityDetail() {
	}

	public CommodityDetail(CommodityBase commodityBase, String detailCode,
			String introduction, String remark) {
		this.commodityBase = commodityBase;
		this.detailCode = detailCode;
		this.introduction = introduction;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodity) {
		this.commodityBase = commodity;
	}

	public String getDetailCode() {
		return this.detailCode;
	}

	public void setDetailCode(String detailCode) {
		this.detailCode = detailCode;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
