package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CommodityPayment generated by hbm2java
 */
public class CommodityPayment implements java.io.Serializable {

	private Integer id;
	private CommodityOrder commodityOrder;
	private BigDecimal sum;
	private String payType;
	private Date payTime;
	private String status;
	private String remark;
	private Set<PointConsumeLog> pointConsumeLogs = new HashSet<PointConsumeLog>(
			0);
	private Set<Coupon> coupons = new HashSet<Coupon>(0);

	public CommodityPayment() {
	}

	public CommodityPayment(CommodityOrder commodityOrder, BigDecimal sum,
			Date payTime) {
		this.commodityOrder = commodityOrder;
		this.sum = sum;
		this.payTime = payTime;
	}

	public CommodityPayment(CommodityOrder commodityOrder, BigDecimal sum,
			String payType, Date payTime, String status, String remark,
			Set<PointConsumeLog> pointConsumeLogs, Set<Coupon> coupons) {
		this.commodityOrder = commodityOrder;
		this.sum = sum;
		this.payType = payType;
		this.payTime = payTime;
		this.status = status;
		this.remark = remark;
		this.pointConsumeLogs = pointConsumeLogs;
		this.coupons = coupons;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CommodityOrder getCommodityOrder() {
		return this.commodityOrder;
	}

	public void setCommodityOrder(CommodityOrder commodityOrder) {
		this.commodityOrder = commodityOrder;
	}

	public BigDecimal getSum() {
		return this.sum;
	}

	public void setSum(BigDecimal sum) {
		this.sum = sum;
	}

	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public Date getPayTime() {
		return this.payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<PointConsumeLog> getPointConsumeLogs() {
		return this.pointConsumeLogs;
	}

	public void setPointConsumeLogs(Set<PointConsumeLog> pointConsumeLogs) {
		this.pointConsumeLogs = pointConsumeLogs;
	}

	public Set<Coupon> getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Set<Coupon> coupons) {
		this.coupons = coupons;
	}

}
