package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CommodityOrder generated by hbm2java
 */
public class CommodityOrder implements java.io.Serializable {

	private Integer id;
	private User user;
	private User deliveryToUser;
	private Area area;
	private Date dealTime;
	private String payType;
	private String quickRequest;
	private String quickPropose;
	private BigDecimal freight;
	private String deliveryAddress;
	private Date deliveryTime;
	private String deliveryman;
	private String postcode;
	private String contact;
	private String contactPhone;
	private Date updateTime;
	private String status;
	private String remark;
	private String orderType;
	private Date planDeliveryTime;
	private String memo;
	private String comment;
	private Set<PointLog> pointLogs = new HashSet<PointLog>(0);
	private Set<CommodityPayment> commodityPayments = new HashSet<CommodityPayment>(
			0);
	private Set<CommodityOrderItem> commodityOrderItems = new HashSet<CommodityOrderItem>(
			0);
    private Set<BillCommodityOrder> billCommodityOrders = new HashSet<BillCommodityOrder>(0);

	public CommodityOrder() {
	}

	public CommodityOrder(Date dealTime, Date deliveryTime, Date updateTime,
			Date planDeliveryTime) {
		this.dealTime = dealTime;
		this.deliveryTime = deliveryTime;
		this.updateTime = updateTime;
		this.planDeliveryTime = planDeliveryTime;
	}

	public CommodityOrder(User user, Area area,User deliveryToUser, Date dealTime, String payType,
			BigDecimal freight, String deliveryAddress, Date deliveryTime,
			String deliveryman, String postcode, String contact,
			String contactPhone, Date updateTime, String status, String remark,
			String orderType, Date planDeliveryTime, String memo,
			String comment, Set<PointLog> pointLogs,
			Set<CommodityPayment> commodityPayments,
			Set<CommodityOrderItem> commodityOrderItems,
			Set<BillCommodityOrder> billCommodityOrders) {
		this.user = user;
		this.area = area;
		this.deliveryToUser = deliveryToUser;
		this.dealTime = dealTime;
		this.payType = payType;
		this.freight = freight;
		this.deliveryAddress = deliveryAddress;
		this.deliveryTime = deliveryTime;
		this.deliveryman = deliveryman;
		this.postcode = postcode;
		this.contact = contact;
		this.contactPhone = contactPhone;
		this.updateTime = updateTime;
		this.status = status;
		this.remark = remark;
		this.orderType = orderType;
		this.planDeliveryTime = planDeliveryTime;
		this.memo = memo;
		this.comment = comment;
		this.pointLogs = pointLogs;
		this.commodityPayments = commodityPayments;
		this.commodityOrderItems = commodityOrderItems;
	    this.billCommodityOrders = billCommodityOrders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public User getDeliveryToUser() {
		return deliveryToUser;
	}

	public void setDeliveryToUser(User deliveryToUser) {
		this.deliveryToUser = deliveryToUser;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Date getDealTime() {
		return this.dealTime;
	}

	public void setDealTime(Date dealTime) {
		this.dealTime = dealTime;
	}

	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public BigDecimal getFreight() {
		return this.freight;
	}

	public void setFreight(BigDecimal freight) {
		this.freight = freight;
	}

	public String getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	public String getDeliveryman() {
		return this.deliveryman;
	}

	public void setDeliveryman(String deliveryman) {
		this.deliveryman = deliveryman;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	public Date getPlanDeliveryTime() {
		return this.planDeliveryTime;
	}

	public void setPlanDeliveryTime(Date planDeliveryTime) {
		this.planDeliveryTime = planDeliveryTime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Set<PointLog> getPointLogs() {
		return this.pointLogs;
	}

	public void setPointLogs(Set<PointLog> pointLogs) {
		this.pointLogs = pointLogs;
	}

	public Set<CommodityPayment> getCommodityPayments() {
		return this.commodityPayments;
	}

	public void setCommodityPayments(Set<CommodityPayment> commodityPayments) {
		this.commodityPayments = commodityPayments;
	}

	public Set<CommodityOrderItem> getCommodityOrderItems() {
		return this.commodityOrderItems;
	}

	public void setCommodityOrderItems(
			Set<CommodityOrderItem> commodityOrderItems) {
		this.commodityOrderItems = commodityOrderItems;
	}

	public String getQuickRequest() {
		return quickRequest;
	}

	public void setQuickRequest(String quickRequest) {
		this.quickRequest = quickRequest;
	}

	public String getQuickPropose() {
		return quickPropose;
	}

	public void setQuickPropose(String quickPropose) {
		this.quickPropose = quickPropose;
	}
	
    public Set<BillCommodityOrder> getBillCommodityOrders() {
        return this.billCommodityOrders;
    }
    
    public void setBillCommodityOrders(Set<BillCommodityOrder> billCommodityOrders) {
        this.billCommodityOrders = billCommodityOrders;
    }

}
