package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

/**
 * CommodityPicture generated by hbm2java
 */
public class CommodityBasePicture implements java.io.Serializable {

	private Integer id;
	private CommodityBase commodityBase;
	private String path;
	private String category;
	private String description;
	private String remark;

	public CommodityBasePicture() {
	}

	public CommodityBasePicture(CommodityBase commodityBase, String path, String category,
			String description, String remark) {
		this.commodityBase = commodityBase;
		this.path = path;
		this.category = category;
		this.description = description;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodity) {
		this.commodityBase = commodity;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
