package com.runtech.onlineshop.model;

// Generated Nov 5, 2011 5:52:18 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commodity generated by hbm2java
 */
public class CommodityBase implements java.io.Serializable {

	private Integer id;
	private String name;
	private String shortName;
	private String summary;
	private String picturePath;
	private String status;
	private Integer updater;
	private Date updateTime;
	private String remark;
	private Set<CommodityBasePicture> commodityBasePictures = new HashSet<CommodityBasePicture>(
			0);
	private Set<CommodityDetail> commodityDetails = new HashSet<CommodityDetail>(
			0);

	public CommodityBase() {
	}

	public CommodityBase(
			String name, String shortName, String picturePath,
			String status,
			Date updateTime) {
		this.name = name;
		this.shortName = shortName;
		this.status = status;
		this.picturePath = picturePath;
		this.updateTime = updateTime;
	}

	public CommodityBase(String name, String shortName,
			String summary,String picturePath,
			String status,
			Integer updater, Date updateTime, String remark,
			Set<CommodityBasePicture> commodityBasePictures,
			Set<CommodityDetail> commodityDetails) {
		this.name = name;
		this.shortName = shortName;
		this.summary = summary;
		this.picturePath = picturePath;
		this.status = status;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.commodityBasePictures = commodityBasePictures;
		this.commodityDetails = commodityDetails;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getSummary() {
		return summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getPicturePath() {
		return picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getUpdater() {
		return updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<CommodityBasePicture> getCommodityBasePictures() {
		return commodityBasePictures;
	}

	public void setCommodityBasePictures(Set<CommodityBasePicture> commodityBasePictures) {
		this.commodityBasePictures = commodityBasePictures;
	}

	public Set<CommodityDetail> getCommodityDetails() {
		return commodityDetails;
	}

	public void setCommodityDetails(Set<CommodityDetail> commodityDetails) {
		this.commodityDetails = commodityDetails;
	}


}
