package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * CommodityComment generated by hbm2java
 */
public class CommodityComment implements java.io.Serializable {

	private Integer id;
	private User user;
	private Commodity commodity;
	private String content;
	private Date commentTime;
	private Integer commentLevel;
	private String remark;

	public CommodityComment() {
	}

	public CommodityComment(Integer id, Commodity commodity, Date commentTime) {
		this.id = id;
		this.commodity = commodity;
		this.commentTime = commentTime;
	}

	public CommodityComment(Integer id, User user, Commodity commodity,
			String content, Date commentTime, Integer commentLevel,
			String remark) {
		this.id = id;
		this.user = user;
		this.commodity = commodity;
		this.content = content;
		this.commentTime = commentTime;
		this.commentLevel = commentLevel;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	public Integer getCommentLevel() {
		return this.commentLevel;
	}

	public void setCommentLevel(Integer commentLevel) {
		this.commentLevel = commentLevel;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
