package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

/**
 * LabelContent generated by hbm2java
 */
public class LabelContent implements java.io.Serializable {

	private LabelContentId id;
	private Content content;
	private LabelWord labelWord;
	private String status;
	private String remark;

	public LabelContent() {
	}

	public LabelContent(LabelContentId id, Content content, LabelWord labelWord) {
		this.id = id;
		this.content = content;
		this.labelWord = labelWord;
	}

	public LabelContent(LabelContentId id, Content content,
			LabelWord labelWord, String status, String remark) {
		this.id = id;
		this.content = content;
		this.labelWord = labelWord;
		this.status = status;
		this.remark = remark;
	}

	public LabelContentId getId() {
		return this.id;
	}

	public void setId(LabelContentId id) {
		this.id = id;
	}

	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	public LabelWord getLabelWord() {
		return this.labelWord;
	}

	public void setLabelWord(LabelWord labelWord) {
		this.labelWord = labelWord;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
