package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

/**
 * LabelCommodity generated by hbm2java
 */
public class LabelCommodity implements java.io.Serializable {

	private LabelCommodityId id;
	private LabelWord labelWord;
	private Commodity commodity;
	private String status;
	private String remark;

	public LabelCommodity() {
	}

	public LabelCommodity(LabelCommodityId id, LabelWord labelWord,
			Commodity commodity) {
		this.id = id;
		this.labelWord = labelWord;
		this.commodity = commodity;
	}

	public LabelCommodity(LabelCommodityId id, LabelWord labelWord,
			Commodity commodity, String status, String remark) {
		this.id = id;
		this.labelWord = labelWord;
		this.commodity = commodity;
		this.status = status;
		this.remark = remark;
	}

	public LabelCommodityId getId() {
		return this.id;
	}

	public void setId(LabelCommodityId id) {
		this.id = id;
	}

	public LabelWord getLabelWord() {
		return this.labelWord;
	}

	public void setLabelWord(LabelWord labelWord) {
		this.labelWord = labelWord;
	}

	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
