package com.runtech.onlineshop.model;

// Generated Mar 31, 2010 11:13:15 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LabelWords generated by hbm2java
 */
public class LabelWords implements java.io.Serializable {

	private String labelName;
	private Date updateTime;
	private Integer updater;
	private String remark;
	private Set<LabelCommodity> labelCommodities = new HashSet<LabelCommodity>(
			0);

	public LabelWords() {
	}

	public LabelWords(String labelName, Date updateTime) {
		this.labelName = labelName;
		this.updateTime = updateTime;
	}

	public LabelWords(String labelName, Date updateTime, Integer updater,
			String remark, Set<LabelCommodity> labelCommodities) {
		this.labelName = labelName;
		this.updateTime = updateTime;
		this.updater = updater;
		this.remark = remark;
		this.labelCommodities = labelCommodities;
	}

	public String getLabelName() {
		return this.labelName;
	}

	public void setLabelName(String labelName) {
		this.labelName = labelName;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<LabelCommodity> getLabelCommodities() {
		return this.labelCommodities;
	}

	public void setLabelCommodities(Set<LabelCommodity> labelCommodities) {
		this.labelCommodities = labelCommodities;
	}

}
