package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

/**
 * PageTemplateComponent generated by hbm2java
 */
public class PageTemplateComponent implements java.io.Serializable {

	private PageTemplateComponentId id;
	private PageTemplate pageTemplate;
	private PageComponent pageComponent;
	private String referenceName;
	private String status;
	private String remark;

	public PageTemplateComponent() {
	}

	public PageTemplateComponent(PageTemplateComponentId id,
			PageTemplate pageTemplate, PageComponent pageComponent) {
		this.id = id;
		this.pageTemplate = pageTemplate;
		this.pageComponent = pageComponent;
	}

	public PageTemplateComponent(PageTemplateComponentId id,
			PageTemplate pageTemplate, PageComponent pageComponent,
			String referenceName, String status, String remark) {
		this.id = id;
		this.pageTemplate = pageTemplate;
		this.pageComponent = pageComponent;
		this.referenceName = referenceName;
		this.status = status;
		this.remark = remark;
	}

	public PageTemplateComponentId getId() {
		return this.id;
	}

	public void setId(PageTemplateComponentId id) {
		this.id = id;
	}

	public PageTemplate getPageTemplate() {
		return this.pageTemplate;
	}

	public void setPageTemplate(PageTemplate pageTemplate) {
		this.pageTemplate = pageTemplate;
	}

	public PageComponent getPageComponent() {
		return this.pageComponent;
	}

	public void setPageComponent(PageComponent pageComponent) {
		this.pageComponent = pageComponent;
	}

	public String getReferenceName() {
		return this.referenceName;
	}

	public void setReferenceName(String referenceName) {
		this.referenceName = referenceName;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
