package com.runtech.onlineshop.model;

// Generated Dec 23, 2011 3:16:11 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * SmsContent generated by hbm2java
 */
public class SmsContent implements java.io.Serializable {

	private Integer id;
	private String content;
	private Integer updater;
	private Date updateTime;
	private String remark;

	public SmsContent() {
	}

	public SmsContent(Integer id, String content, Date updateTime) {
		this.id = id;
		this.content = content;
		this.updateTime = updateTime;
	}

	public SmsContent(Integer id, String content, Integer updater,
			Date updateTime, String remark) {
		this.id = id;
		this.content = content;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
