package com.runtech.onlineshop.model;

// Generated Dec 23, 2011 3:16:11 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SmsGroup generated by hbm2java
 */
public class SmsGroup implements java.io.Serializable {

	private Integer id;
	private String groupName;
	private Integer updater;
	private Date updateTime;
	private String status;
	private String remark;
	private Set<SmsContact> smsContacts = new HashSet<SmsContact>(0);

	public SmsGroup() {
	}

	public SmsGroup(Integer id, String groupName, Date updateTime) {
		this.id = id;
		this.groupName = groupName;
		this.updateTime = updateTime;
	}

	public SmsGroup(Integer id, String groupName, Integer updater,
			Date updateTime, String status, String remark,
			Set<SmsContact> smsContacts) {
		this.id = id;
		this.groupName = groupName;
		this.updater = updater;
		this.updateTime = updateTime;
		this.status = status;
		this.remark = remark;
		this.smsContacts = smsContacts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<SmsContact> getSmsContacts() {
		return this.smsContacts;
	}

	public void setSmsContacts(Set<SmsContact> smsContacts) {
		this.smsContacts = smsContacts;
	}

}
