package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SystemCode generated by hbm2java
 */
public class SystemCode implements java.io.Serializable {

	private Integer id;
	private SystemCode systemCode;
	private String code;
	private String name;
	private String category;
	private Integer priority;
	private Integer updater;
	private Date updateTime;
	private String status;
	private String remark;
	private Set<SystemCode> systemCodes = new HashSet<SystemCode>(0);

	public SystemCode() {
	}

	public SystemCode(String code, String name, String category,
			Integer priority, Date updateTime) {
		this.code = code;
		this.name = name;
		this.category = category;
		this.priority = priority;
		this.updateTime = updateTime;
	}

	public SystemCode(SystemCode systemCode, String code, String name,
			String category, Integer priority, Integer updater,
			Date updateTime, String status, String remark,
			Set<SystemCode> systemCodes) {
		this.systemCode = systemCode;
		this.code = code;
		this.name = name;
		this.category = category;
		this.priority = priority;
		this.updater = updater;
		this.updateTime = updateTime;
		this.status = status;
		this.remark = remark;
		this.systemCodes = systemCodes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SystemCode getSystemCode() {
		return this.systemCode;
	}

	public void setSystemCode(SystemCode systemCode) {
		this.systemCode = systemCode;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<SystemCode> getSystemCodes() {
		return this.systemCodes;
	}

	public void setSystemCodes(Set<SystemCode> systemCodes) {
		this.systemCodes = systemCodes;
	}

}
