package com.runtech.onlineshop.model;

// Generated Jul 24, 2013 2:11:05 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import java.util.Date;

/**
 * UserContract generated by hbm2java
 */
public class UserContract implements java.io.Serializable {

	private Integer id;
	private User user;
	private Admin admin;
	private Admin updater;
	private String contractType;
	private Date startTime;
	private Date endTime;
	private String contractContent;
	private String contractFile;
	private Date signTime;
	private Date updateTime;
	private Blob file;
	private String status;
	private String remark;

	public UserContract() {
	}

	public UserContract(User user, String contractType, Date startTime,
			Date endTime, Date signTime, Date updateTime) {
		this.user = user;
		this.contractType = contractType;
		this.startTime = startTime;
		this.endTime = endTime;
		this.signTime = signTime;
		this.updateTime = updateTime;
	}

	public UserContract(User user, Admin adminByServiceAdmin,
			Admin adminByUpdater, String contractType, Date startTime,
			Date endTime, String contractContent, String contractFile,
			Date signTime, Date updateTime, Blob file, String status,
			String remark) {
		this.user = user;
		this.admin = adminByServiceAdmin;
		this.updater = adminByUpdater;
		this.contractType = contractType;
		this.startTime = startTime;
		this.endTime = endTime;
		this.contractContent = contractContent;
		this.contractFile = contractFile;
		this.signTime = signTime;
		this.updateTime = updateTime;
		this.file = file;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin adminByServiceAdmin) {
		this.admin = adminByServiceAdmin;
	}

	public Admin getUpdater() {
		return this.updater;
	}

	public void setUpdater(Admin adminByUpdater) {
		this.updater = adminByUpdater;
	}

	public String getContractType() {
		return this.contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getContractContent() {
		return this.contractContent;
	}

	public void setContractContent(String contractContent) {
		this.contractContent = contractContent;
	}

	public String getContractFile() {
		return this.contractFile;
	}

	public void setContractFile(String contractFile) {
		this.contractFile = contractFile;
	}

	public Date getSignTime() {
		return this.signTime;
	}

	public void setSignTime(Date signTime) {
		this.signTime = signTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Blob getFile() {
		return this.file;
	}

	public void setFile(Blob file) {
		this.file = file;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
