package com.runtech.onlineshop.model;

// Generated Apr 18, 2010 5:12:23 PM by Hibernate Tools 3.2.4.GA

/**
 * UserDetail generated by hbm2java
 */
public class UserDetail implements java.io.Serializable {

	private Integer id;
	private User user;
	private String introduction;
	private String question;
	private String answer;
	private String remark;

	public UserDetail() {
	}

	public UserDetail(User user) {
		this.user = user;
	}

	public UserDetail(User user, String introduction, String question,
			String answer, String remark) {
		this.user = user;
		this.introduction = introduction;
		this.question = question;
		this.answer = answer;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
