package com.runtech.onlineshop.model;

// Generated Jul 22, 2013 8:33:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserLoginLog generated by hbm2java
 */
public class UserLoginLog implements java.io.Serializable {

	private Integer id;
	private User user;
	private String loginMachine;
	private String loginFrom;
	private Boolean loginResult;
	private Date loginTime;

	public UserLoginLog() {
	}

	public UserLoginLog(Integer id, User user, Boolean loginResult,
			Date loginTime) {
		this.id = id;
		this.user = user;
		this.loginResult = loginResult;
		this.loginTime = loginTime;
	}

	public UserLoginLog(Integer id, User user, String loginMachine,
			String loginFrom, Boolean loginResult, Date loginTime) {
		this.id = id;
		this.user = user;
		this.loginMachine = loginMachine;
		this.loginFrom = loginFrom;
		this.loginResult = loginResult;
		this.loginTime = loginTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getLoginMachine() {
		return this.loginMachine;
	}

	public void setLoginMachine(String loginMachine) {
		this.loginMachine = loginMachine;
	}

	public String getLoginFrom() {
		return this.loginFrom;
	}

	public void setLoginFrom(String loginFrom) {
		this.loginFrom = loginFrom;
	}

	public Boolean getLoginResult() {
		return this.loginResult;
	}

	public void setLoginResult(Boolean loginResult) {
		this.loginResult = loginResult;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

}
