package com.runtech.onlineshop.model;

// Generated Jul 9, 2013 11:58:27 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private Area area;
	private User recommendUser;
	private Admin admin;
	private User parentUser;
	private String name;
	private String password;
	private String fullName;
	private String userType;
	private String subUserType;
	private Integer importance;
	private Integer age;
	private String sex;
	private String email;
	private String phone;
	private String mobile;
	private String contact;
	private String contactPosition;
	private String contactQq;
	private String contactOther;
	private String website;
	private String fax;
	private Date lastMaintainTime;
	private String sinaAuthorization;
	private String qqAuthorization;
	private String credentialType;
	private String credentialNumber;
	private BigDecimal point;
	private BigDecimal empiricValue;
	private Integer level;
	private String address;
	private String status;
	private String picturePath;
	private Date registerTime;
	private Admin updater;
	private Date updateTime;
	private String remark;

	private Set<UserLoginLog> userLoginLogs = new HashSet<UserLoginLog>(0);
	private Set<QuickOrder> quickOrders = new HashSet<QuickOrder>(0);
	private UserDetail userDetail;
	private Set<FavoriteCommodity> favoriteCommodities = new HashSet<FavoriteCommodity>(
			0);
	private Set<UserContract> userContracts = new HashSet<UserContract>(0);
	private Set<FavoriteContent> favoriteContents = new HashSet<FavoriteContent>(
			0);
	private Set<User> linkUsers = new HashSet<User>(0);
	private Set<User> subOrganizationUsers = new HashSet<User>(0);
	private Set<User> subIndividualUsers = new HashSet<User>(0);

	private Set<User> subUsers = new HashSet<User>(0);
	private Set<PointLog> pointLogs = new HashSet<PointLog>(0);
	private Set<UserMaintainLog> userMaintainLogs = new HashSet<UserMaintainLog>(
			0);
	private Set<CommodityOrder> commodityOrders = new HashSet<CommodityOrder>(0);
	private Set<CommodityOrder> deliveryCommodityOrders = new HashSet<CommodityOrder>(0);
	private Set<CommodityComment> commodityComments = new HashSet<CommodityComment>(
			0);
	private Set<DeliveryContact> deliveryContacts = new HashSet<DeliveryContact>(
			0);

	public User() {
	}

	public User(Integer id, String name, String password, String email,
			Date lastMaintainTime, String status, Date registerTime,
			Date updateTime) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.email = email;
		this.lastMaintainTime = lastMaintainTime;
		this.status = status;
		this.registerTime = registerTime;
		this.updateTime = updateTime;
	}

	public User(Integer id, Area area, User userByRecommendUserId, Admin admin,
			User userByParentUserId, String name, String password,
			String fullName, String userType, String subUserType,
			Integer importance, Integer age, String sex, String email,
			String phone, String mobile, String contact, String contactPosition, String contactQq,
			String contactOther, String website, String fax,
			Date lastMaintainTime, String sinaAuthorization,
			String qqAuthorization, String credentialType,
			String credentialNumber, BigDecimal point, BigDecimal empiricValue,
			Integer level, String address, String status, String picturePath,
			Date registerTime, Admin updater, Date updateTime, String remark,
			Set<User> usersForParentUserId, Set<QuickOrder> quickOrders,
			UserDetail userDetail, Set<UserContract> userContracts,
			Set<User> usersForRecommendUserId, Set<PointLog> pointLogs,
			Set<CommodityOrder> commodityOrdersForDeliveryToUserId,
			Set<UserMaintainLog> userMaintainLogs,
			Set<CommodityOrder> commodityOrdersForUserId,
			Set<CommodityComment> commodityComments,
			Set<DeliveryContact> deliveryContacts) {
		this.id = id;
		this.area = area;
		this.recommendUser = userByRecommendUserId;
		this.admin = admin;
		this.parentUser = userByParentUserId;
		this.name = name;
		this.password = password;
		this.fullName = fullName;
		this.userType = userType;
		this.subUserType = subUserType;
		this.importance = importance;
		this.age = age;
		this.sex = sex;
		this.email = email;
		this.phone = phone;
		this.mobile = mobile;
		this.contact = contact;
		this.contactPosition = contactPosition;
		this.contactQq = contactQq;
		this.contactOther = contactOther;
		this.website = website;
		this.fax = fax;
		this.lastMaintainTime = lastMaintainTime;
		this.sinaAuthorization = sinaAuthorization;
		this.qqAuthorization = qqAuthorization;
		this.credentialType = credentialType;
		this.credentialNumber = credentialNumber;
		this.point = point;
		this.empiricValue = empiricValue;
		this.level = level;
		this.address = address;
		this.status = status;
		this.picturePath = picturePath;
		this.registerTime = registerTime;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.subUsers = usersForParentUserId;
		this.quickOrders = quickOrders;
		this.userDetail = userDetail;
		this.userContracts = userContracts;
		this.linkUsers = usersForRecommendUserId;
		this.pointLogs = pointLogs;
		this.deliveryCommodityOrders = commodityOrdersForDeliveryToUserId;
		this.userMaintainLogs = userMaintainLogs;
		this.commodityOrders = commodityOrdersForUserId;
		this.commodityComments = commodityComments;
		this.deliveryContacts = deliveryContacts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public User getRecommendUser() {
		return this.recommendUser;
	}

	public void setRecommendUser(User userByRecommendUserId) {
		this.recommendUser = userByRecommendUserId;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getSubUserType() {
		return this.subUserType;
	}

	public void setSubUserType(String subUserType) {
		this.subUserType = subUserType;
	}

	public Integer getImportance() {
		return this.importance;
	}

	public void setImportance(Integer importance) {
		this.importance = importance;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getContactPosition() {
		return contactPosition;
	}

	public void setContactPosition(String contactPosition) {
		this.contactPosition = contactPosition;
	}

	public String getContactQq() {
		return this.contactQq;
	}

	public void setContactQq(String contactQq) {
		this.contactQq = contactQq;
	}

	public String getContactOther() {
		return this.contactOther;
	}

	public void setContactOther(String contactOther) {
		this.contactOther = contactOther;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Date getLastMaintainTime() {
		return this.lastMaintainTime;
	}

	public void setLastMaintainTime(Date lastMaintainTime) {
		this.lastMaintainTime = lastMaintainTime;
	}

	public String getSinaAuthorization() {
		return this.sinaAuthorization;
	}

	public void setSinaAuthorization(String sinaAuthorization) {
		this.sinaAuthorization = sinaAuthorization;
	}

	public String getQqAuthorization() {
		return this.qqAuthorization;
	}

	public void setQqAuthorization(String qqAuthorization) {
		this.qqAuthorization = qqAuthorization;
	}

	public String getCredentialType() {
		return this.credentialType;
	}

	public void setCredentialType(String credentialType) {
		this.credentialType = credentialType;
	}

	public String getCredentialNumber() {
		return this.credentialNumber;
	}

	public void setCredentialNumber(String credentialNumber) {
		this.credentialNumber = credentialNumber;
	}

	public BigDecimal getPoint() {
		return this.point;
	}

	public void setPoint(BigDecimal point) {
		this.point = point;
	}

	public BigDecimal getEmpiricValue() {
		return this.empiricValue;
	}

	public void setEmpiricValue(BigDecimal empiricValue) {
		this.empiricValue = empiricValue;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public Admin getUpdater() {
		return this.updater;
	}

	public void setUpdater(Admin updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public User getParentUser() {
		return this.parentUser;
	}

	public void setParentUser(User parentUser) {
		this.parentUser = parentUser;
	}

	public Set<QuickOrder> getQuickOrders() {
		return this.quickOrders;
	}

	public void setQuickOrders(Set<QuickOrder> quickOrders) {
		this.quickOrders = quickOrders;
	}

	public Set<UserLoginLog> getUserLoginLogs() {
		return userLoginLogs;
	}

	public void setUserLoginLogs(Set<UserLoginLog> userLoginLogs) {
		this.userLoginLogs = userLoginLogs;
	}

	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public Set<FavoriteCommodity> getFavoriteCommodities() {
		return this.favoriteCommodities;
	}

	public void setFavoriteCommodities(
			Set<FavoriteCommodity> favoriteCommodities) {
		this.favoriteCommodities = favoriteCommodities;
	}

	public Set<UserContract> getUserContracts() {
		return this.userContracts;
	}

	public void setUserContracts(Set<UserContract> userContracts) {
		this.userContracts = userContracts;
	}

	public Set<FavoriteContent> getFavoriteContents() {
		return this.favoriteContents;
	}

	public void setFavoriteContents(Set<FavoriteContent> favoriteContents) {
		this.favoriteContents = favoriteContents;
	}

	public Set<User> getLinkUsers() {
		return this.linkUsers;
	}

	public void setLinkUsers(Set<User> users) {
		this.linkUsers = users;
	}

	public Set<PointLog> getPointLogs() {
		return this.pointLogs;
	}

	public void setPointLogs(Set<PointLog> pointLogs) {
		this.pointLogs = pointLogs;
	}

	public Set<UserMaintainLog> getUserMaintainLogs() {
		return this.userMaintainLogs;
	}

	public void setUserMaintainLogs(Set<UserMaintainLog> userMaintainLogs) {
		this.userMaintainLogs = userMaintainLogs;
	}

	public Set<CommodityOrder> getCommodityOrders() {
		return this.commodityOrders;
	}

	public void setCommodityOrders(Set<CommodityOrder> commodityOrders) {
		this.commodityOrders = commodityOrders;
	}

	public Set<CommodityOrder> getDeliveryCommodityOrders() {
		return deliveryCommodityOrders;
	}

	public void setDeliveryCommodityOrders(
			Set<CommodityOrder> deliveryCommodityOrders) {
		this.deliveryCommodityOrders = deliveryCommodityOrders;
	}

	public Set<CommodityComment> getCommodityComments() {
		return this.commodityComments;
	}

	public void setCommodityComments(Set<CommodityComment> commodityComments) {
		this.commodityComments = commodityComments;
	}

	public Set<DeliveryContact> getDeliveryContacts() {
		return this.deliveryContacts;
	}

	public void setDeliveryContacts(Set<DeliveryContact> deliveryContacts) {
		this.deliveryContacts = deliveryContacts;
	}

	public Set<User> getSubUsers() {
		return subUsers;
	}

	public void setSubUsers(Set<User> subUsers) {
		this.subUsers = subUsers;
	}

	public Set<User> getSubOrganizationUsers() {
		return subOrganizationUsers;
	}

	public void setSubOrganizationUsers(Set<User> subOrganizationUsers) {
		this.subOrganizationUsers = subOrganizationUsers;
	}

	public Set<User> getSubIndividualUsers() {
		return subIndividualUsers;
	}

	public void setSubIndividualUsers(Set<User> subIndividualUsers) {
		this.subIndividualUsers = subIndividualUsers;
	}
}
