package com.runtech.onlineshop.model;

import com.runtech.web.dao.ModelHome;
import com.runtech.web.dispatcher.RuntechContext;
import com.runtech.web.form.FlowableForm;
import com.runtech.web.runtime.ModelException;

// Generated Jul 22, 2013 5:00:52 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkFlow generated by hbm2java
 */
public class WorkFlow implements java.io.Serializable {

	private Integer id;
	private AdminRole adminRole;
	private String workFlowName;
	private String workFlowDetail;
	private String documentType;
	private String documentStatus;
	private String reviewedStatus;
	private String rejectedStatus;
	private String remark;

	public WorkFlow() {
	}

	public WorkFlow(AdminRole adminRole, String workFlowName,
			String documentType, String documentStatus, String reviewedStatus,
			String rejectedStatus) {
		this.adminRole = adminRole;
		this.workFlowName = workFlowName;
		this.documentType = documentType;
		this.documentStatus = documentStatus;
		this.reviewedStatus = reviewedStatus;
		this.rejectedStatus = rejectedStatus;
	}

	public WorkFlow(AdminRole adminRole, String workFlowName,
			String workFlowDetail, String documentType, String documentStatus,
			String reviewedStatus, String rejectedStatus, String remark) {
		this.adminRole = adminRole;
		this.workFlowName = workFlowName;
		this.workFlowDetail = workFlowDetail;
		this.documentType = documentType;
		this.documentStatus = documentStatus;
		this.reviewedStatus = reviewedStatus;
		this.rejectedStatus = rejectedStatus;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AdminRole getAdminRole() {
		return this.adminRole;
	}

	public void setAdminRole(AdminRole adminRole) {
		this.adminRole = adminRole;
	}

	public String getWorkFlowName() {
		return this.workFlowName;
	}

	public void setWorkFlowName(String workFlowName) {
		this.workFlowName = workFlowName;
	}

	public String getWorkFlowDetail() {
		return this.workFlowDetail;
	}

	public void setWorkFlowDetail(String workFlowDetail) {
		this.workFlowDetail = workFlowDetail;
	}

	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public String getDocumentStatus() {
		return this.documentStatus;
	}

	public void setDocumentStatus(String documentStatus) {
		this.documentStatus = documentStatus;
	}

	public String getReviewedStatus() {
		return this.reviewedStatus;
	}

	public void setReviewedStatus(String reviewedStatus) {
		this.reviewedStatus = reviewedStatus;
	}

	public String getRejectedStatus() {
		return this.rejectedStatus;
	}

	public void setRejectedStatus(String rejectedStatus) {
		this.rejectedStatus = rejectedStatus;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
