package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private Integer id;
	private Area area;
	private String code;
	private String name;
	private String category;
	private Integer priority;
	private Integer updater;
	private Date updateTime;
	private String status;
	private String remark;
	private Set<Area> areas = new HashSet<Area>(0);
	private Set<Commodity> commodities = new HashSet<Commodity>(0);
	private Set<QuickOrder> quickOrders = new HashSet<QuickOrder>(0);
	private Set<DeliveryContact> deliveryContacts = new HashSet<DeliveryContact>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<CommodityOrder> commodityOrders = new HashSet<CommodityOrder>(0);

	public Area() {
	}

	public Area(String code, String name, String category, Integer priority, Date updateTime) {
		this.code = code;
		this.name = name;
		this.category = category;
		this.priority = priority;
		this.updateTime = updateTime;
	}

	public Area(Area area, String code, String name, String category, Integer priority, Integer updater,
			Date updateTime, String status, String remark, Set<Area> areas, Set<Commodity> commodities,
			Set<QuickOrder> quickOrders, Set<DeliveryContact> deliveryContacts, Set<User> users,
			Set<CommodityOrder> commodityOrders) {
		this.area = area;
		this.code = code;
		this.name = name;
		this.category = category;
		this.priority = priority;
		this.updater = updater;
		this.updateTime = updateTime;
		this.status = status;
		this.remark = remark;
		this.areas = areas;
		this.commodities = commodities;
		this.quickOrders = quickOrders;
		this.deliveryContacts = deliveryContacts;
		this.users = users;
		this.commodityOrders = commodityOrders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

	public Set<Commodity> getCommodities() {
		return this.commodities;
	}

	public void setCommodities(Set<Commodity> commodities) {
		this.commodities = commodities;
	}

	public Set<QuickOrder> getQuickOrders() {
		return this.quickOrders;
	}

	public void setQuickOrders(Set<QuickOrder> quickOrders) {
		this.quickOrders = quickOrders;
	}

	public Set<DeliveryContact> getDeliveryContacts() {
		return this.deliveryContacts;
	}

	public void setDeliveryContacts(Set<DeliveryContact> deliveryContacts) {
		this.deliveryContacts = deliveryContacts;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<CommodityOrder> getCommodityOrders() {
		return this.commodityOrders;
	}

	public void setCommodityOrders(Set<CommodityOrder> commodityOrders) {
		this.commodityOrders = commodityOrders;
	}

}
