package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

/**
 * CommodityDetail generated by hbm2java
 */
public class CommodityDetail implements java.io.Serializable {

	private Integer id;
	private CommodityBase commodityBase;
	private String detailCode;
	private String introduction;
	private String remark;

	public CommodityDetail() {
	}

	public CommodityDetail(Integer id) {
		this.id = id;
	}

	public CommodityDetail(Integer id, CommodityBase commodityBase, String detailCode, String introduction,
			String remark) {
		this.id = id;
		this.commodityBase = commodityBase;
		this.detailCode = detailCode;
		this.introduction = introduction;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodityBase) {
		this.commodityBase = commodityBase;
	}

	public String getDetailCode() {
		return this.detailCode;
	}

	public void setDetailCode(String detailCode) {
		this.detailCode = detailCode;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
