package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * CommodityOrderItem generated by hbm2java
 */
public class CommodityOrderItem implements java.io.Serializable {

	private Integer id;
	private CommodityOrder commodityOrder;
	private Commodity commodity;
	private CommodityPromotion commodityPromotion;
	private Integer commodityNumber;
	private BigDecimal price;
	private BigDecimal discount;
	private BigDecimal realPrice;
	private Integer point;
	private Integer rate;
	private String comment;
	private String status;
	private String remark;

	public CommodityOrderItem() {
	}

	public CommodityOrderItem(CommodityOrder commodityOrder, Commodity commodity, Integer commodityNumber) {
		this.commodityOrder = commodityOrder;
		this.commodity = commodity;
		this.commodityNumber = commodityNumber;
	}

	public CommodityOrderItem(CommodityOrder commodityOrder, Commodity commodity, CommodityPromotion commodityPromotion,
			Integer commodityNumber, BigDecimal price, BigDecimal discount, BigDecimal realPrice, Integer point,
			Integer rate, String comment, String status, String remark) {
		this.commodityOrder = commodityOrder;
		this.commodity = commodity;
		this.commodityPromotion = commodityPromotion;
		this.commodityNumber = commodityNumber;
		this.price = price;
		this.discount = discount;
		this.realPrice = realPrice;
		this.point = point;
		this.rate = rate;
		this.comment = comment;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CommodityOrder getCommodityOrder() {
		return this.commodityOrder;
	}

	public void setCommodityOrder(CommodityOrder commodityOrder) {
		this.commodityOrder = commodityOrder;
	}

	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	public CommodityPromotion getCommodityPromotion() {
		return this.commodityPromotion;
	}

	public void setCommodityPromotion(CommodityPromotion commodityPromotion) {
		this.commodityPromotion = commodityPromotion;
	}

	public Integer getCommodityNumber() {
		return this.commodityNumber;
	}

	public void setCommodityNumber(Integer commodityNumber) {
		this.commodityNumber = commodityNumber;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public BigDecimal getRealPrice() {
		return this.realPrice;
	}

	public void setRealPrice(BigDecimal realPrice) {
		this.realPrice = realPrice;
	}

	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	public Integer getRate() {
		return this.rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
