package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Coupon generated by hbm2java
 */
public class Coupon implements java.io.Serializable {

	private Integer id;
	private CommodityPayment commodityPayment;
	private String name;
	private String number;
	private BigDecimal value;
	private BigDecimal requireOrderSum;
	private Date startDate;
	private Date expireDate;
	private Date createTime;
	private Date comsumeTime;
	private String status;
	private String remark;

	public Coupon() {
	}

	public Coupon(String name, String number, BigDecimal value, BigDecimal requireOrderSum, Date startDate,
			Date expireDate, Date createTime, Date comsumeTime) {
		this.name = name;
		this.number = number;
		this.value = value;
		this.requireOrderSum = requireOrderSum;
		this.startDate = startDate;
		this.expireDate = expireDate;
		this.createTime = createTime;
		this.comsumeTime = comsumeTime;
	}

	public Coupon(CommodityPayment commodityPayment, String name, String number, BigDecimal value,
			BigDecimal requireOrderSum, Date startDate, Date expireDate, Date createTime, Date comsumeTime,
			String status, String remark) {
		this.commodityPayment = commodityPayment;
		this.name = name;
		this.number = number;
		this.value = value;
		this.requireOrderSum = requireOrderSum;
		this.startDate = startDate;
		this.expireDate = expireDate;
		this.createTime = createTime;
		this.comsumeTime = comsumeTime;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CommodityPayment getCommodityPayment() {
		return this.commodityPayment;
	}

	public void setCommodityPayment(CommodityPayment commodityPayment) {
		this.commodityPayment = commodityPayment;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	public BigDecimal getRequireOrderSum() {
		return this.requireOrderSum;
	}

	public void setRequireOrderSum(BigDecimal requireOrderSum) {
		this.requireOrderSum = requireOrderSum;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getComsumeTime() {
		return this.comsumeTime;
	}

	public void setComsumeTime(Date comsumeTime) {
		this.comsumeTime = comsumeTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
