package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

/**
 * LabelContent generated by hbm2java
 */
public class LabelContent implements java.io.Serializable {

	private LabelContentId id;
	private LabelWord labelWord;
	private Content content;
	private String status;
	private String remark;

	public LabelContent() {
	}

	public LabelContent(LabelContentId id, LabelWord labelWord, Content content) {
		this.id = id;
		this.labelWord = labelWord;
		this.content = content;
	}

	public LabelContent(LabelContentId id, LabelWord labelWord, Content content, String status, String remark) {
		this.id = id;
		this.labelWord = labelWord;
		this.content = content;
		this.status = status;
		this.remark = remark;
	}

	public LabelContentId getId() {
		return this.id;
	}

	public void setId(LabelContentId id) {
		this.id = id;
	}

	public LabelWord getLabelWord() {
		return this.labelWord;
	}

	public void setLabelWord(LabelWord labelWord) {
		this.labelWord = labelWord;
	}

	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
