package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PageTemplate generated by hbm2java
 */
public class PageTemplate implements java.io.Serializable {

	private Integer id;
	private String name;
	private String language;
	private String template;
	private String status;
	private Integer updater;
	private Date updateTime;
	private String remark;
	private Set<PageTemplateComponent> pageTemplateComponents = new HashSet<PageTemplateComponent>(0);
	private Set<SiteModule> siteModules = new HashSet<SiteModule>(0);

	public PageTemplate() {
	}

	public PageTemplate(Date updateTime) {
		this.updateTime = updateTime;
	}

	public PageTemplate(String name, String language, String template, String status, Integer updater, Date updateTime,
			String remark, Set<PageTemplateComponent> pageTemplateComponents, Set<SiteModule> siteModules) {
		this.name = name;
		this.language = language;
		this.template = template;
		this.status = status;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.pageTemplateComponents = pageTemplateComponents;
		this.siteModules = siteModules;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<PageTemplateComponent> getPageTemplateComponents() {
		return this.pageTemplateComponents;
	}

	public void setPageTemplateComponents(Set<PageTemplateComponent> pageTemplateComponents) {
		this.pageTemplateComponents = pageTemplateComponents;
	}

	public Set<SiteModule> getSiteModules() {
		return this.siteModules;
	}

	public void setSiteModules(Set<SiteModule> siteModules) {
		this.siteModules = siteModules;
	}

}
