package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PointLog generated by hbm2java
 */
public class PointLog implements java.io.Serializable {

	private Integer id;
	private User user;
	private CommodityOrder commodityOrder;
	private String typeCode;
	private BigDecimal point;
	private Date pointTime;
	private String remark;

	public PointLog() {
	}

	public PointLog(Date pointTime) {
		this.pointTime = pointTime;
	}

	public PointLog(User user, CommodityOrder commodityOrder, String typeCode, BigDecimal point, Date pointTime,
			String remark) {
		this.user = user;
		this.commodityOrder = commodityOrder;
		this.typeCode = typeCode;
		this.point = point;
		this.pointTime = pointTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public CommodityOrder getCommodityOrder() {
		return this.commodityOrder;
	}

	public void setCommodityOrder(CommodityOrder commodityOrder) {
		this.commodityOrder = commodityOrder;
	}

	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	public BigDecimal getPoint() {
		return this.point;
	}

	public void setPoint(BigDecimal point) {
		this.point = point;
	}

	public Date getPointTime() {
		return this.pointTime;
	}

	public void setPointTime(Date pointTime) {
		this.pointTime = pointTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
