package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ReferralLog generated by hbm2java
 */
public class ReferralLog implements java.io.Serializable {

	private Integer id;
	private String userMobile;
	private String introducerMobile;
	private String introducerName;
	private Date introduceTime;
	private String status;
	private String remark;

	public ReferralLog() {
	}

	public ReferralLog(Integer id, String userMobile, String introducerMobile, String introducerName,
			Date introduceTime) {
		this.id = id;
		this.userMobile = userMobile;
		this.introducerMobile = introducerMobile;
		this.introducerName = introducerName;
		this.introduceTime = introduceTime;
	}

	public ReferralLog(Integer id, String userMobile, String introducerMobile, String introducerName,
			Date introduceTime, String status, String remark) {
		this.id = id;
		this.userMobile = userMobile;
		this.introducerMobile = introducerMobile;
		this.introducerName = introducerName;
		this.introduceTime = introduceTime;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserMobile() {
		return this.userMobile;
	}

	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	public String getIntroducerMobile() {
		return this.introducerMobile;
	}

	public void setIntroducerMobile(String introducerMobile) {
		this.introducerMobile = introducerMobile;
	}

	public String getIntroducerName() {
		return this.introducerName;
	}

	public void setIntroducerName(String introducerName) {
		this.introducerName = introducerName;
	}

	public Date getIntroduceTime() {
		return this.introduceTime;
	}

	public void setIntroduceTime(Date introduceTime) {
		this.introduceTime = introduceTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
