package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ReportConfiguration generated by hbm2java
 */
public class ReportConfiguration implements java.io.Serializable {

	private Integer id;
	private String name;
	private String query;
	private String template;
	private String form;
	private String status;
	private Integer updater;
	private Date updateTime;
	private String remark;

	public ReportConfiguration() {
	}

	public ReportConfiguration(Integer id, String query, String template, String status, Date updateTime) {
		this.id = id;
		this.query = query;
		this.template = template;
		this.status = status;
		this.updateTime = updateTime;
	}

	public ReportConfiguration(Integer id, String name, String query, String template, String form, String status,
			Integer updater, Date updateTime, String remark) {
		this.id = id;
		this.name = name;
		this.query = query;
		this.template = template;
		this.form = form;
		this.status = status;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public String getForm() {
		return this.form;
	}

	public void setForm(String form) {
		this.form = form;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
