package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SmsSentLog generated by hbm2java
 */
public class SmsSentLog implements java.io.Serializable {

	private Integer id;
	private String content;
	private String recipients;
	private Integer sender;
	private Date sendTime;
	private String status;
	private String remark;

	public SmsSentLog() {
	}

	public SmsSentLog(String content, Date sendTime) {
		this.content = content;
		this.sendTime = sendTime;
	}

	public SmsSentLog(String content, String recipients, Integer sender, Date sendTime, String status, String remark) {
		this.content = content;
		this.recipients = recipients;
		this.sender = sender;
		this.sendTime = sendTime;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getRecipients() {
		return this.recipients;
	}

	public void setRecipients(String recipients) {
		this.recipients = recipients;
	}

	public Integer getSender() {
		return this.sender;
	}

	public void setSender(Integer sender) {
		this.sender = sender;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
