package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

/**
 * SurveyItem generated by hbm2java
 */
public class SurveyItem implements java.io.Serializable {

	private Integer id;
	private Survey survey;
	private String description;
	private String link;
	private String referType;
	private Integer referId;
	private Integer count;
	private Integer priority;
	private String remark;

	public SurveyItem() {
	}

	public SurveyItem(Integer id, Survey survey, String description, Integer count) {
		this.id = id;
		this.survey = survey;
		this.description = description;
		this.count = count;
	}

	public SurveyItem(Integer id, Survey survey, String description, String link, String referType, Integer referId,
			Integer count, Integer priority, String remark) {
		this.id = id;
		this.survey = survey;
		this.description = description;
		this.link = link;
		this.referType = referType;
		this.referId = referId;
		this.count = count;
		this.priority = priority;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getReferType() {
		return this.referType;
	}

	public void setReferType(String referType) {
		this.referType = referType;
	}

	public Integer getReferId() {
		return this.referId;
	}

	public void setReferId(Integer referId) {
		this.referId = referId;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
