package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserMaintainLog generated by hbm2java
 */
public class UserMaintainLog implements java.io.Serializable {

	private Integer id;
	private User user;
	private Admin adminByUpdater;
	private Admin adminByAdminId;
	private Date maintainTime;
	private String summary;
	private String detail;
	private Date updateTime;
	private String opportunity;
	private BigDecimal opportunityValue;
	private BigDecimal opportunityPossibility;
	private Date opportunityTime;
	private String opportunityStatus;
	private Integer reviewer;
	private String reviewComments;
	private String status;
	private String remark;

	public UserMaintainLog() {
	}

	public UserMaintainLog(Date maintainTime, Date updateTime) {
		this.maintainTime = maintainTime;
		this.updateTime = updateTime;
	}

	public UserMaintainLog(User user, Admin adminByUpdater, Admin adminByAdminId, Date maintainTime, String summary,
			String detail, Date updateTime, String opportunity, BigDecimal opportunityValue,
			BigDecimal opportunityPossibility, Date opportunityTime, String opportunityStatus, Integer reviewer,
			String reviewComments, String status, String remark) {
		this.user = user;
		this.adminByUpdater = adminByUpdater;
		this.adminByAdminId = adminByAdminId;
		this.maintainTime = maintainTime;
		this.summary = summary;
		this.detail = detail;
		this.updateTime = updateTime;
		this.opportunity = opportunity;
		this.opportunityValue = opportunityValue;
		this.opportunityPossibility = opportunityPossibility;
		this.opportunityTime = opportunityTime;
		this.opportunityStatus = opportunityStatus;
		this.reviewer = reviewer;
		this.reviewComments = reviewComments;
		this.status = status;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Admin getAdminByUpdater() {
		return this.adminByUpdater;
	}

	public void setAdminByUpdater(Admin adminByUpdater) {
		this.adminByUpdater = adminByUpdater;
	}

	public Admin getAdminByAdminId() {
		return this.adminByAdminId;
	}

	public void setAdminByAdminId(Admin adminByAdminId) {
		this.adminByAdminId = adminByAdminId;
	}

	public Date getMaintainTime() {
		return this.maintainTime;
	}

	public void setMaintainTime(Date maintainTime) {
		this.maintainTime = maintainTime;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getOpportunity() {
		return this.opportunity;
	}

	public void setOpportunity(String opportunity) {
		this.opportunity = opportunity;
	}

	public BigDecimal getOpportunityValue() {
		return this.opportunityValue;
	}

	public void setOpportunityValue(BigDecimal opportunityValue) {
		this.opportunityValue = opportunityValue;
	}

	public BigDecimal getOpportunityPossibility() {
		return this.opportunityPossibility;
	}

	public void setOpportunityPossibility(BigDecimal opportunityPossibility) {
		this.opportunityPossibility = opportunityPossibility;
	}

	public Date getOpportunityTime() {
		return this.opportunityTime;
	}

	public void setOpportunityTime(Date opportunityTime) {
		this.opportunityTime = opportunityTime;
	}

	public String getOpportunityStatus() {
		return this.opportunityStatus;
	}

	public void setOpportunityStatus(String opportunityStatus) {
		this.opportunityStatus = opportunityStatus;
	}

	public Integer getReviewer() {
		return this.reviewer;
	}

	public void setReviewer(Integer reviewer) {
		this.reviewer = reviewer;
	}

	public String getReviewComments() {
		return this.reviewComments;
	}

	public void setReviewComments(String reviewComments) {
		this.reviewComments = reviewComments;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
