package com.runtech.onlineshop.model;
// Generated 2015-7-23 13:12:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private Admin adminByUpdater;
	private Area area;
	private User userByRecommendUserId;
	private User userByParentUserId;
	private Admin adminByServiceAdmin;
	private String name;
	private String password;
	private String fullName;
	private String userType;
	private String subUserType;
	private Integer importance;
	private Integer age;
	private String sex;
	private String email;
	private String phone;
	private String mobile;
	private String contact;
	private String contactPosition;
	private String contactQq;
	private String contactOther;
	private String website;
	private String fax;
	private Date lastMaintainTime;
	private String sinaAuthorization;
	private String qqAuthorization;
	private String credentialType;
	private String credentialNumber;
	private BigDecimal point;
	private BigDecimal empiricValue;
	private Integer level;
	private String address;
	private String status;
	private String picturePath;
	private Date registerTime;
	private Date updateTime;
	private String remark;
	private Set<UserContract> userContracts = new HashSet<UserContract>(0);
	private UserDetail userDetail;
	private Set<CommodityOrder> commodityOrdersForUserId = new HashSet<CommodityOrder>(0);
	private Set<CommodityComment> commodityComments = new HashSet<CommodityComment>(0);
	private Set<CommodityOrder> commodityOrdersForDeliveryToUserId = new HashSet<CommodityOrder>(0);
	private Set<DeliveryContact> deliveryContacts = new HashSet<DeliveryContact>(0);
	private Set<PointLog> pointLogs = new HashSet<PointLog>(0);
	private Set<UserLoginLog> userLoginLogs = new HashSet<UserLoginLog>(0);
	private Set<User> usersForParentUserId = new HashSet<User>(0);
	private Set<UserMaintainLog> userMaintainLogs = new HashSet<UserMaintainLog>(0);
	private Set<QuickOrder> quickOrders = new HashSet<QuickOrder>(0);
	private Set<User> usersForRecommendUserId = new HashSet<User>(0);

	public User() {
	}

	public User(String name, String password, Date lastMaintainTime, String status, Date registerTime,
			Date updateTime) {
		this.name = name;
		this.password = password;
		this.lastMaintainTime = lastMaintainTime;
		this.status = status;
		this.registerTime = registerTime;
		this.updateTime = updateTime;
	}

	public User(Admin adminByUpdater, Area area, User userByRecommendUserId, User userByParentUserId,
			Admin adminByServiceAdmin, String name, String password, String fullName, String userType,
			String subUserType, Integer importance, Integer age, String sex, String email, String phone, String mobile,
			String contact, String contactPosition, String contactQq, String contactOther, String website, String fax,
			Date lastMaintainTime, String sinaAuthorization, String qqAuthorization, String credentialType,
			String credentialNumber, BigDecimal point, BigDecimal empiricValue, Integer level, String address,
			String status, String picturePath, Date registerTime, Date updateTime, String remark,
			Set<UserContract> userContracts, UserDetail userDetail, Set<CommodityOrder> commodityOrdersForUserId,
			Set<CommodityComment> commodityComments, Set<CommodityOrder> commodityOrdersForDeliveryToUserId,
			Set<DeliveryContact> deliveryContacts, Set<PointLog> pointLogs, Set<UserLoginLog> userLoginLogs,
			Set<User> usersForParentUserId, Set<UserMaintainLog> userMaintainLogs, Set<QuickOrder> quickOrders,
			Set<User> usersForRecommendUserId) {
		this.adminByUpdater = adminByUpdater;
		this.area = area;
		this.userByRecommendUserId = userByRecommendUserId;
		this.userByParentUserId = userByParentUserId;
		this.adminByServiceAdmin = adminByServiceAdmin;
		this.name = name;
		this.password = password;
		this.fullName = fullName;
		this.userType = userType;
		this.subUserType = subUserType;
		this.importance = importance;
		this.age = age;
		this.sex = sex;
		this.email = email;
		this.phone = phone;
		this.mobile = mobile;
		this.contact = contact;
		this.contactPosition = contactPosition;
		this.contactQq = contactQq;
		this.contactOther = contactOther;
		this.website = website;
		this.fax = fax;
		this.lastMaintainTime = lastMaintainTime;
		this.sinaAuthorization = sinaAuthorization;
		this.qqAuthorization = qqAuthorization;
		this.credentialType = credentialType;
		this.credentialNumber = credentialNumber;
		this.point = point;
		this.empiricValue = empiricValue;
		this.level = level;
		this.address = address;
		this.status = status;
		this.picturePath = picturePath;
		this.registerTime = registerTime;
		this.updateTime = updateTime;
		this.remark = remark;
		this.userContracts = userContracts;
		this.userDetail = userDetail;
		this.commodityOrdersForUserId = commodityOrdersForUserId;
		this.commodityComments = commodityComments;
		this.commodityOrdersForDeliveryToUserId = commodityOrdersForDeliveryToUserId;
		this.deliveryContacts = deliveryContacts;
		this.pointLogs = pointLogs;
		this.userLoginLogs = userLoginLogs;
		this.usersForParentUserId = usersForParentUserId;
		this.userMaintainLogs = userMaintainLogs;
		this.quickOrders = quickOrders;
		this.usersForRecommendUserId = usersForRecommendUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Admin getAdminByUpdater() {
		return this.adminByUpdater;
	}

	public void setAdminByUpdater(Admin adminByUpdater) {
		this.adminByUpdater = adminByUpdater;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public User getUserByRecommendUserId() {
		return this.userByRecommendUserId;
	}

	public void setUserByRecommendUserId(User userByRecommendUserId) {
		this.userByRecommendUserId = userByRecommendUserId;
	}

	public User getUserByParentUserId() {
		return this.userByParentUserId;
	}

	public void setUserByParentUserId(User userByParentUserId) {
		this.userByParentUserId = userByParentUserId;
	}

	public Admin getAdminByServiceAdmin() {
		return this.adminByServiceAdmin;
	}

	public void setAdminByServiceAdmin(Admin adminByServiceAdmin) {
		this.adminByServiceAdmin = adminByServiceAdmin;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getSubUserType() {
		return this.subUserType;
	}

	public void setSubUserType(String subUserType) {
		this.subUserType = subUserType;
	}

	public Integer getImportance() {
		return this.importance;
	}

	public void setImportance(Integer importance) {
		this.importance = importance;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getContactPosition() {
		return this.contactPosition;
	}

	public void setContactPosition(String contactPosition) {
		this.contactPosition = contactPosition;
	}

	public String getContactQq() {
		return this.contactQq;
	}

	public void setContactQq(String contactQq) {
		this.contactQq = contactQq;
	}

	public String getContactOther() {
		return this.contactOther;
	}

	public void setContactOther(String contactOther) {
		this.contactOther = contactOther;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Date getLastMaintainTime() {
		return this.lastMaintainTime;
	}

	public void setLastMaintainTime(Date lastMaintainTime) {
		this.lastMaintainTime = lastMaintainTime;
	}

	public String getSinaAuthorization() {
		return this.sinaAuthorization;
	}

	public void setSinaAuthorization(String sinaAuthorization) {
		this.sinaAuthorization = sinaAuthorization;
	}

	public String getQqAuthorization() {
		return this.qqAuthorization;
	}

	public void setQqAuthorization(String qqAuthorization) {
		this.qqAuthorization = qqAuthorization;
	}

	public String getCredentialType() {
		return this.credentialType;
	}

	public void setCredentialType(String credentialType) {
		this.credentialType = credentialType;
	}

	public String getCredentialNumber() {
		return this.credentialNumber;
	}

	public void setCredentialNumber(String credentialNumber) {
		this.credentialNumber = credentialNumber;
	}

	public BigDecimal getPoint() {
		return this.point;
	}

	public void setPoint(BigDecimal point) {
		this.point = point;
	}

	public BigDecimal getEmpiricValue() {
		return this.empiricValue;
	}

	public void setEmpiricValue(BigDecimal empiricValue) {
		this.empiricValue = empiricValue;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<UserContract> getUserContracts() {
		return this.userContracts;
	}

	public void setUserContracts(Set<UserContract> userContracts) {
		this.userContracts = userContracts;
	}

	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public Set<CommodityOrder> getCommodityOrdersForUserId() {
		return this.commodityOrdersForUserId;
	}

	public void setCommodityOrdersForUserId(Set<CommodityOrder> commodityOrdersForUserId) {
		this.commodityOrdersForUserId = commodityOrdersForUserId;
	}

	public Set<CommodityComment> getCommodityComments() {
		return this.commodityComments;
	}

	public void setCommodityComments(Set<CommodityComment> commodityComments) {
		this.commodityComments = commodityComments;
	}

	public Set<CommodityOrder> getCommodityOrdersForDeliveryToUserId() {
		return this.commodityOrdersForDeliveryToUserId;
	}

	public void setCommodityOrdersForDeliveryToUserId(Set<CommodityOrder> commodityOrdersForDeliveryToUserId) {
		this.commodityOrdersForDeliveryToUserId = commodityOrdersForDeliveryToUserId;
	}

	public Set<DeliveryContact> getDeliveryContacts() {
		return this.deliveryContacts;
	}

	public void setDeliveryContacts(Set<DeliveryContact> deliveryContacts) {
		this.deliveryContacts = deliveryContacts;
	}

	public Set<PointLog> getPointLogs() {
		return this.pointLogs;
	}

	public void setPointLogs(Set<PointLog> pointLogs) {
		this.pointLogs = pointLogs;
	}

	public Set<UserLoginLog> getUserLoginLogs() {
		return this.userLoginLogs;
	}

	public void setUserLoginLogs(Set<UserLoginLog> userLoginLogs) {
		this.userLoginLogs = userLoginLogs;
	}

	public Set<User> getUsersForParentUserId() {
		return this.usersForParentUserId;
	}

	public void setUsersForParentUserId(Set<User> usersForParentUserId) {
		this.usersForParentUserId = usersForParentUserId;
	}

	public Set<UserMaintainLog> getUserMaintainLogs() {
		return this.userMaintainLogs;
	}

	public void setUserMaintainLogs(Set<UserMaintainLog> userMaintainLogs) {
		this.userMaintainLogs = userMaintainLogs;
	}

	public Set<QuickOrder> getQuickOrders() {
		return this.quickOrders;
	}

	public void setQuickOrders(Set<QuickOrder> quickOrders) {
		this.quickOrders = quickOrders;
	}

	public Set<User> getUsersForRecommendUserId() {
		return this.usersForRecommendUserId;
	}

	public void setUsersForRecommendUserId(Set<User> usersForRecommendUserId) {
		this.usersForRecommendUserId = usersForRecommendUserId;
	}

}
