package com.runtech.onlineshop.model;

// Generated Sep 22, 2013 5:21:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WorkFlowLog generated by hbm2java
 */
public class WorkFlowLog implements java.io.Serializable {

	private Integer id;
	private Admin adminBySubmitter;
	private WorkFlow workFlow;
	private Admin adminByReviewer;
	private String documentType;
	private Integer documentId;
	private Date reviewTime;
	private String previousStatus;
	private String afterStatus;
	private String comments;
	private String remark;

	public WorkFlowLog() {
	}

	public WorkFlowLog(Integer id, Admin adminByReviewer, String documentType,
			Integer documentId, Date reviewTime, String previousStatus,
			String afterStatus) {
		this.id = id;
		this.adminByReviewer = adminByReviewer;
		this.documentType = documentType;
		this.documentId = documentId;
		this.reviewTime = reviewTime;
		this.previousStatus = previousStatus;
		this.afterStatus = afterStatus;
	}

	public WorkFlowLog(Integer id, Admin adminBySubmitter, WorkFlow workFlow,
			Admin adminByReviewer, String documentType, Integer documentId,
			Date reviewTime, String previousStatus, String afterStatus,
			String comments, String remark) {
		this.id = id;
		this.adminBySubmitter = adminBySubmitter;
		this.workFlow = workFlow;
		this.adminByReviewer = adminByReviewer;
		this.documentType = documentType;
		this.documentId = documentId;
		this.reviewTime = reviewTime;
		this.previousStatus = previousStatus;
		this.afterStatus = afterStatus;
		this.comments = comments;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Admin getAdminBySubmitter() {
		return this.adminBySubmitter;
	}

	public void setAdminBySubmitter(Admin adminBySubmitter) {
		this.adminBySubmitter = adminBySubmitter;
	}

	public WorkFlow getWorkFlow() {
		return this.workFlow;
	}

	public void setWorkFlow(WorkFlow workFlow) {
		this.workFlow = workFlow;
	}

	public Admin getAdminByReviewer() {
		return this.adminByReviewer;
	}

	public void setAdminByReviewer(Admin adminByReviewer) {
		this.adminByReviewer = adminByReviewer;
	}

	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}

	public String getPreviousStatus() {
		return this.previousStatus;
	}

	public void setPreviousStatus(String previousStatus) {
		this.previousStatus = previousStatus;
	}

	public String getAfterStatus() {
		return this.afterStatus;
	}

	public void setAfterStatus(String afterStatus) {
		this.afterStatus = afterStatus;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
