package com.runtech.onlineshop.model;
// Generated 2016-5-4 9:52:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdminLoginLog generated by hbm2java
 */
public class AdminLoginLog implements java.io.Serializable {

	private Integer id;
	private Admin admin;
	private String loginMachine;
	private String loginFrom;
	private boolean loginResult;
	private Date loginTime;

	public AdminLoginLog() {
	}

	public AdminLoginLog(Admin admin, boolean loginResult, Date loginTime) {
		this.admin = admin;
		this.loginResult = loginResult;
		this.loginTime = loginTime;
	}

	public AdminLoginLog(Admin admin, String loginMachine, String loginFrom, boolean loginResult, Date loginTime) {
		this.admin = admin;
		this.loginMachine = loginMachine;
		this.loginFrom = loginFrom;
		this.loginResult = loginResult;
		this.loginTime = loginTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getLoginMachine() {
		return this.loginMachine;
	}

	public void setLoginMachine(String loginMachine) {
		this.loginMachine = loginMachine;
	}

	public String getLoginFrom() {
		return this.loginFrom;
	}

	public void setLoginFrom(String loginFrom) {
		this.loginFrom = loginFrom;
	}

	public boolean isLoginResult() {
		return this.loginResult;
	}

	public void setLoginResult(boolean loginResult) {
		this.loginResult = loginResult;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

}
