package com.runtech.onlineshop.model;
// Generated 2016-5-4 9:52:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer id;
	private AdminRole adminRole;
	private String name;
	private String password;
	private String fullName;
	private String email;
	private String phone;
	private String mobile;
	private String address;
	private String status;
	private Integer updater;
	private Date updateTime;
	private String remark;
	private Set<User> usersForUpdater = new HashSet<User>(0);
	private Set<CommodityProvider> commodityProviders = new HashSet<CommodityProvider>(0);
	private Set<User> usersForServiceAdmin = new HashSet<User>(0);
	private Set<AdminLoginLog> adminLoginLogs = new HashSet<AdminLoginLog>(0);

	public Admin() {
	}

	public Admin(AdminRole adminRole, String name, String password, String email, String status, Date updateTime) {
		this.adminRole = adminRole;
		this.name = name;
		this.password = password;
		this.email = email;
		this.status = status;
		this.updateTime = updateTime;
	}

	public Admin(AdminRole adminRole, String name, String password, String fullName, String email, String phone,
			String mobile, String address, String status, Integer updater, Date updateTime, String remark,
			Set<User> usersForUpdater, Set<CommodityProvider> commodityProviders, Set<User> usersForServiceAdmin,
			Set<AdminLoginLog> adminLoginLogs) {
		this.adminRole = adminRole;
		this.name = name;
		this.password = password;
		this.fullName = fullName;
		this.email = email;
		this.phone = phone;
		this.mobile = mobile;
		this.address = address;
		this.status = status;
		this.updater = updater;
		this.updateTime = updateTime;
		this.remark = remark;
		this.usersForUpdater = usersForUpdater;
		this.commodityProviders = commodityProviders;
		this.usersForServiceAdmin = usersForServiceAdmin;
		this.adminLoginLogs = adminLoginLogs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AdminRole getAdminRole() {
		return this.adminRole;
	}

	public void setAdminRole(AdminRole adminRole) {
		this.adminRole = adminRole;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<User> getUsersForUpdater() {
		return this.usersForUpdater;
	}

	public void setUsersForUpdater(Set<User> usersForUpdater) {
		this.usersForUpdater = usersForUpdater;
	}

	public Set<CommodityProvider> getCommodityProviders() {
		return this.commodityProviders;
	}

	public void setCommodityProviders(Set<CommodityProvider> commodityProviders) {
		this.commodityProviders = commodityProviders;
	}

	public Set<User> getUsersForServiceAdmin() {
		return this.usersForServiceAdmin;
	}

	public void setUsersForServiceAdmin(Set<User> usersForServiceAdmin) {
		this.usersForServiceAdmin = usersForServiceAdmin;
	}

	public Set<AdminLoginLog> getAdminLoginLogs() {
		return this.adminLoginLogs;
	}

	public void setAdminLoginLogs(Set<AdminLoginLog> adminLoginLogs) {
		this.adminLoginLogs = adminLoginLogs;
	}

}
