package com.runtech.onlineshop.model;
// Generated 2016-5-4 9:52:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consignment generated by hbm2java
 */
public class Consignment implements java.io.Serializable {

	private Integer id;
	private String consignmentTitle;
	private String consignmentDescription;
	private String consignmentOperator;
	private String consignmentPosition;
	private String consignmentCompany;
	private String consignmentCompanyAcn;
	private String consignmentCompanyTaxNo;
	private Date createTime;
	private Date deliveryTime;
	private String status;
	private String comment;
	private Set<CommodityOrder> commodityOrders = new HashSet<CommodityOrder>(0);
	private Set<ConsignmentPicture> consignmentPictures = new HashSet<ConsignmentPicture>(0);

	public Consignment() {
	}

	public Consignment(Date createTime) {
		this.createTime = createTime;
	}

	public Consignment(String consignmentTitle, String consignmentDescription, String consignmentOperator,
			String consignmentPosition, String consignmentCompany, String consignmentCompanyAcn,
			String consignmentCompanyTaxNo, Date createTime, Date deliveryTime, String status, String comment,
			Set<CommodityOrder> commodityOrders, Set<ConsignmentPicture> consignmentPictures) {
		this.consignmentTitle = consignmentTitle;
		this.consignmentDescription = consignmentDescription;
		this.consignmentOperator = consignmentOperator;
		this.consignmentPosition = consignmentPosition;
		this.consignmentCompany = consignmentCompany;
		this.consignmentCompanyAcn = consignmentCompanyAcn;
		this.consignmentCompanyTaxNo = consignmentCompanyTaxNo;
		this.createTime = createTime;
		this.deliveryTime = deliveryTime;
		this.status = status;
		this.comment = comment;
		this.commodityOrders = commodityOrders;
		this.consignmentPictures = consignmentPictures;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getConsignmentTitle() {
		return this.consignmentTitle;
	}

	public void setConsignmentTitle(String consignmentTitle) {
		this.consignmentTitle = consignmentTitle;
	}

	public String getConsignmentDescription() {
		return this.consignmentDescription;
	}

	public void setConsignmentDescription(String consignmentDescription) {
		this.consignmentDescription = consignmentDescription;
	}

	public String getConsignmentOperator() {
		return this.consignmentOperator;
	}

	public void setConsignmentOperator(String consignmentOperator) {
		this.consignmentOperator = consignmentOperator;
	}

	public String getConsignmentPosition() {
		return this.consignmentPosition;
	}

	public void setConsignmentPosition(String consignmentPosition) {
		this.consignmentPosition = consignmentPosition;
	}

	public String getConsignmentCompany() {
		return this.consignmentCompany;
	}

	public void setConsignmentCompany(String consignmentCompany) {
		this.consignmentCompany = consignmentCompany;
	}

	public String getConsignmentCompanyAcn() {
		return this.consignmentCompanyAcn;
	}

	public void setConsignmentCompanyAcn(String consignmentCompanyAcn) {
		this.consignmentCompanyAcn = consignmentCompanyAcn;
	}

	public String getConsignmentCompanyTaxNo() {
		return this.consignmentCompanyTaxNo;
	}

	public void setConsignmentCompanyTaxNo(String consignmentCompanyTaxNo) {
		this.consignmentCompanyTaxNo = consignmentCompanyTaxNo;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Set<CommodityOrder> getCommodityOrders() {
		return this.commodityOrders;
	}

	public void setCommodityOrders(Set<CommodityOrder> commodityOrders) {
		this.commodityOrders = commodityOrders;
	}

	public Set<ConsignmentPicture> getConsignmentPictures() {
		return this.consignmentPictures;
	}

	public void setConsignmentPictures(Set<ConsignmentPicture> consignmentPictures) {
		this.consignmentPictures = consignmentPictures;
	}

}
